### ISSUE TITLE
echo "http://$(curl ifconfig.io):5000" && nvidia-docker run --ipc=host -p 5000:5000 -it deoldify_api

### ISSUE THREAD

**Issue by isgbuddy** [jantic/DeOldify#111]
This command seem show need Nvidia-docker here? docker-api run only CPU? My server don't have GPU here.

**Comment by jqueguiner** [comment]
For now I didn’t adapt it to Non GPU mode but I’ll try soon however it will be veeeerrrrrryyyyy slllloooow

**Comment by jantic** [comment]
@jqueguiner if you want to try doing that, go for it!  CPU support in general isn't something I'm prioritizing myself just because I'm not making DeOldify for everybody and everything.  CPU support/Windows/etc....I'm fond of the word "No".  Now if the submitter of this issue wants to send in a pull request- great!  

I know that having the habit of saying "No" makes me harder to get along with but...it really is one the best sanity saving tricks I know of.

So feel free to just say "No" and I'll close this accordingly.

**Comment by jqueguiner** [comment]
In my experience Pytorch manage easily the cpu mode by checking the gpu device. If it would have been tensorflow it would have been a bit lore complicated. I’ll look into it in 2 weeks ;-)

**Comment by jantic** [comment]
Going to close this.  This seems to be a dead issue.
