### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by 205418367** [jantic/DeOldify#123]
![image](https://user-images.githubusercontent.com/47652945/59265600-413d2080-8c78-11e9-8fcb-aa26dccd36cb.png)

**Comment by jantic** [comment]
So first question I have to ask- what is the operating system you're running?

**Comment by 394781865** [comment]
ubuntu18.04 + cuda10.0 + python3.6

**Comment by 205418367** [comment]
ubuntu18.04 + cuda10.0 + python3.6. I don't use 'conda env create -f environment.yml' ,but use 'pip install -r requirment.txt '. I find this code using torch and what's the version of the torch?

**Comment by jantic** [comment]
I would just use the conda install.  The environment.yml has all the requirements in there (pip install really isn't recommended).  I don't want to encourage anything else.

**Comment by 394781865** [comment]
before I excute 'conda env create -f environment.yml' ,do i need to Install driver and cuda？

**Comment by 205418367** [comment]
before I excute 'conda env create -f environment.yml' ,do i need to Install driver and cuda？

**Comment by jantic** [comment]
Nvidia driver- yes.  CUDA stuff should come along with the fastai portion of the install.

**Comment by recluse27** [comment]
So I did everything the same.
conda -> env -> run -> the same problem

**Comment by jantic** [comment]
So just to be clear- I just wanted to establish a baseline before we go into specifics here, because often there's some "small detail"  that is actually the key issue, like running on Windows instead of Linux.  That being said, the error message itself is stating that there's a permissions issue with the folder. Regardless of the operating system, you'll have to figure out a way to grant permissions to the the folder if they're not there already for the application.  This is where you'll have to exercise some Google-Fu because this isn't a DeOldify problem but rather an environment specfic problem.
