### ISSUE TITLE
What card is best for training?

### ISSUE THREAD

**Issue by shadowzoom** [jantic/DeOldify#131]
If i have budget up to 1000 $ what you an suggest me?

**Comment by jantic** [comment]
In this case you need to make sure to have as much memory as possible.  Otherwise you simply can't train your models effectively (insufficient batch size).  So optimize for that rather than sheer performance.  Second, I've been using 16 bit training on experimental stuff recently but I haven't tackled the issues when running on GANs yet (lots of conversion bugs when switching between 16 bit and 32 bit in fastai unfortunately).  So that's not really an option (to cut down on memory requirements) unless you're prepared to debug and fix the fastai source code.  Finally, I would stick with Nvidia- way better support in the deep learning ecosystem.

That being said, it looks like the good old Nvidia 1080TI is still your best bet (an 11 GB card).  It looks like you may be able to snag it for less than $1000 (on Amazon).  If you can get the 2080 RTX TI and it fits your budget, go for it.  Prices fluctuate so keep that in mind.  

Here's a guide I've found quite helpful:  https://timdettmers.com/2019/04/03/which-gpu-for-deep-learning/

**Comment by xuancao19** [comment]
I don't want to receive your mail again.------------------ 原始邮件 ------------------
发件人: "Jason Antic"<notifications@github.com>
发送时间: 2019年7月18日(星期四) 凌晨2:58
收件人: "jantic/DeOldify"<DeOldify@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [jantic/DeOldify] What card is best for training? (#131)



Closed #131.
 
&mdash;

**Comment by jantic** [comment]
@xuancao19 You'll have to unsubscribe to notifications on this GitHub page then.

Look to the right on the comment thread page:  
![image](https://user-images.githubusercontent.com/179759/61421296-56cae900-a8bb-11e9-94fe-fa2bf3540eee.png)
