### ISSUE TITLE
Improvement of old VHS recordings also possible?

### ISSUE THREAD

**Issue by FSharpCSharp** [jantic/DeOldify#136]
I came across this project by chance, and I'm very excited about it! It shows the big advantages of machine learning and artificial intelligence. It's incredibly impressive, and somehow everyone is directly enthusiastic about it.

But I do have a question after seeing the possibilities. Would it be possible to improve very old VHS recordings significantly? Here there are already colored pictures, but the color layer usually has many errors or there is "bleeding out" of certain colors. Could this be improved and even the artefacts and problems be reduced? There are already several classic filters, but they are all based on mathematical functions and usually lead to the image becoming blurred or a lot of details getting lost. This in turn is partly due to the fact that the content is not recognized. If the whole thing were to be content based, the results would certainly be much better. That would be my guess now.

Oh, and another challenge with VHS would be that the material is interlaced. This means that even more content is lost. To restore this, you would have to create new images between the two fields. But that's another story...

**Comment by jantic** [comment]
In principle, this can be done with the existing DeOldify models retrained on a different dataset tailored for this problem.  Training X images would be your bad VHS images, and Training Y images would be the ideal versions of those same images (just unaltered normal photographs, probably).  Probably the best way to obtain the bad VHS images (Training X) would be to simulate them starting from good normal images (ImageNet etc) and "crappifying" them as described here:  https://www.fast.ai/2019/05/03/decrappify/ .  

The whole business of simulating bad VHS images however isn't trivial, of course.  Perhaps there are filters out there that do that already?  Don't know.  That'd combined with some additional augmentations like blur/noise/warps/contrast/brightness (just like in DeOldify) should all help in training for this task. 

To be clear- I've done super resolution and deblur tasks with the DeOldify model so that's where this confidence comes from.

**Comment by FSharpCSharp** [comment]
@jantic  Many thanks for the detailed answer, and also thanks for the linking of the detailed article. In this case, the ideal approach would be to create test footage, transfer it to VHS and then digitize it again. Thus you get the ideal artefacts, and you don't have to simulate everything first.

But what I'm still wondering is the amount of test data. Would 4 hours of material be enough, or are 12 hours necessary for this? What is your recommendation if you want to use the existing models for this.

**Comment by jantic** [comment]
So that approach sounds great- it sounds a bit labor intensive but if you can do it it would certainly be ideal.  I'd focus on there is diversity of frames (so many different videos with a subset of frames sampled from each).  This is totally spitballing, but I'd think that you'd roughly want to target ImageNet numbers of frames ideally (roughly 1 million):

(1,000,000 frames)/(24 fps)/(3600 seconds in an hour) = about 12 hours of video.  I guess that's how you arrived at that?  If so we're arriving at the same answer then.  It seems to me though you'd really want like a few hundred videos to sample from and that might be the much more important part.  Otherwise you'll be training with too much of overly similar data.
