### ISSUE TITLE
Broken git lfs

### ISSUE THREAD

**Issue by alexandrevicenzi** [jantic/DeOldify#147]
The readme states git lfs, but it does not work (?) because [this commit](https://github.com/jantic/DeOldify/commit/4a7c9c71fc470d0ae0ddc09c9935871eb54a6695) removed all files.

How do I get all test images? and why it was removed from git lfs?

**Comment by jantic** [comment]
I removed them because a few months ago I started racking up a big bill when GitHub finally fixed a bug in their system where they weren't charging for git lfs data usage (which happened to be introduced back in October, right before I introduced my project!).  So when that happened, I was like "oh shit" and just yanked the files out- I can't afford the data for the amount of traffic this repo gets.  I have them in dropbox still, but I wasn't planning on hosting them. They were there purely as a convenience.

**Comment by jantic** [comment]
I guess we could just put comment in the ReadMe indicating this.  Yeah sorry...I just put a stop gap on that then went back to work on whatever I was fixated on at the time (probably staring at Tensorboard).

**Comment by alexandrevicenzi** [comment]
@jantic I understand.

A couple of things should be done:

1. Remove hardcoded file names from notebook if there's no way to get the exact same files
2. Include a note in the readme about this behavior

I have a plan to rework the readme in some sort do documentation and I plan to do this soon.

**Comment by jantic** [comment]
On #1- I liked having the file names there as an example and because well...selfishly, I still have access to the images.  Keep in mind too- the images do much better with specific render factors and that's why there's value in the hardcoding as opposed to just looping through the images blindly in a directory.

That being said, in practice for 99% of people, having a simple loop through a list of files read dynamically from the folder will probably be much more beneficial so let's do that.  Bonus is that it'll be much less code.

On #2- If it's being removed from the notebooks I don't see any reason to have it clarified in the readme personally.

**Comment by alexandrevicenzi** [comment]
@jantic well, the images are still on git history... I have it...

on 1, good idea to loop over files
on 2, we need to remove git lfs from the readme, because it's not available anymore.

**Comment by jantic** [comment]
Agreed on both.  Though I haven't removed the twitter icon from git lfs yet.  A bit silly I know.

**Comment by jantic** [comment]
I've addressed #2 and updated the readme to reflect the current situation with Git LFS.  I decided to just leave the notebooks as is however (explained in the readme).  Here's what it says:

> The images in this folder have been removed because they were using Git LFS and that costs a lot of money when GitHub actually charges for bandwidth on a popular open source project (they had a billing bug for while that was recently fixed). The notebooks that use them (the image test ones) still point to images in that directory that I (Jason) have personally and I'd like to keep it that way because, after all, I'm by far the primary and most active developer. But they won't work for you. Still, those notebooks are a convenient template for making your own tests if you're so inclined.

This seems like the most practical approach IMHO.

**Comment by alexandrevicenzi** [comment]
@jantic sounds good. I just wonder if would be useful to create a dropbox folder with all these images.
