### ISSUE TITLE
proposal: documentation improvement

### ISSUE THREAD

**Issue by alexandrevicenzi** [jantic/DeOldify#149]
The current README in the repo is huge and could be more fashioned. I'm a believer that README's should be straightforward and for developers, not documentation.

There are a couple of options to build an actual documentation and leave the README clean and concise. Here are some:

- Use GitHub Wiki - Simple and easy, but not too Pythonic or good for Python libraries.
- Use Sphinx - reST based, can be powerful, but also complex. Standard tool for Python projects and [readthedocs.org](https://readthedocs.org/) is FREE.
- Use Jekyll - Native GitHub support, but it's in Ruby and for blogs. :-1: 
- Custom website - Nah! Sphinx can also be self hosted.

Personally, I would go with Sphinx. Sphinx can be customized, has a good pattern, tons of projects are using it, I've been using it and it could be hosted on GitHub with gh-pages as well.

The README would only include information about the project setup.

**Comment by jantic** [comment]
So both @dana-kelley  and I agree that we like the readme as is in a lot of ways (perhaps with some cleanup but not a total overhaul).

1. This project isn't strictly for developers.  There's a lot of general user interest.  The readme is more tailored towards that.
2. The readme is full of graphics and video razzle-dazzle because that works to attract attention (I attribute that to why it got picked up by Boing Boing and went viral in the first place).
3. The readme is tailored to answer the kinds of questions that we will inevitably get because many users are simply not going to go out of their way to find the information elsewhere.  In fact, it's hard enough to ask them to RTFM to begin with and many don't even do that.

That being said, I do think it's a great idea to get Sphinx based documentation in place.  THAT will be tailored towards developers for sure.

**Comment by alexandrevicenzi** [comment]
@jantic I understand why the current README is this way, but I'm not sure if I understand what should we do :thinking: 

What should be in Sphinx? and what should be in README?

Based on your "THAT" I believe that README is for general users (explaining the why and how), Sphinx only for devs. As we will release on PyPI, I do believe that makes sense to use Sphinx to explain the code and how to use it to build other applications, but I don't think that Sphinx would be good for how to contribute to this project, for this, I believe that GH Wiki would be better.

Maybe, one thing that could help, is a Table of Contents on the README, similar to [pytorch](https://github.com/pytorch/pytorch). Way easier to navigate.

**Comment by jantic** [comment]
What we're lacking primarily I think is code documentation (usage/api).  That would of course be tailored to devs.  Table of contents in README would be a great.  GH Wiki on how to contribute to the project and other such misc items would be great.

README can be the gateway to point users of various backgrounds to where they need to go (again, table of contents sounds like a great way to do this).  But it should be tailored first and foremost to guide non-developers (to Colabs, what the project is about complete with pictures/videos, etc).   That's generally what I'm getting at.

**Comment by alexandrevicenzi** [comment]
@jantic I started a [wiki page](https://github.com/jantic/DeOldify/wiki) with common questions, I'll try to add more topics and if you have anything feel free to add as well.

**Comment by jantic** [comment]
@alexandrevicenzi Somehow I totally missed this and just realized that you had made the wiki page.  I can't believe I just now realized this.  Belated thank you!

**Comment by alexandrevicenzi** [comment]
Not even I remembered this anymore. Feel free to close this issue if no more work is needed.
