### ISSUE TITLE
Suggestion for speeding up video notebook considerably

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [jantic/DeOldify#154]
First of all, appreciate this repo. 

What I suggest for the video notebook is to _add an option to_* pre-process videos downloaded, and decimate them to remove duplicate frames/frames that are interpolated or low bitrate. You can then match the same overall length of the video changing the frametime/fps in a formula with original length.

I currently do all of this myself in ffmpeg before processing. That way I am not processing multiple duplicate frames for every original frame in videos with bad encoding/wrong encoding. 

If you do this for most videos found on youtube, you could literally reduce frames in most videos by at least 1/3rd, if not 1/2, with no difference at all.

What do you think?

**Comment by jantic** [comment]
This sounds cool.  It should definitely be kept as an option because it sounds like it could be error prone.  Regardless, knocking out 1/3 to 1/2 frames would make quite a bit of difference due to how long these videos take to process (on the order of many minutes to hours). So yeah, if you want to create a pull request that would be great!

**Comment by jantic** [comment]
One more thing- I think by default this should be disabled, unless this functionality proves to be highly reliable.

**Comment by jantic** [comment]
Upon further consideration, this is a bit too much complication being introduced for a relatively small gain.
