### ISSUE TITLE
Run predict in CPU - Solved

### ISSUE THREAD

**Issue by alejandrods** [jantic/DeOldify#157]
Hi, I've got to run the prediction in CPU I will make a pull request from my fork :)

**Comment by alexandrevicenzi** [comment]
@alejandrods any updates on this?

**Comment by alejandrods** [comment]
> @alejandrods any updates on this?

Yeah, I would try to upload the code the next week.

**Comment by alejandrods** [comment]
I have make my pull request some minutes ago. I'm waiting for review

**Comment by gabrielmontagne** [comment]
thanks a lot!

**Comment by jantic** [comment]
I've made the final changes needed and incorporated the work you guys did into it. Thanks!

Usage is described in the notebooks:

`#NOTE:  This must be the first call in order to work properly!
from deoldify import device
from deoldify.device_id import DeviceId
#choices:  CPU, GPU0...GPU7
device.set(device=DeviceId.GPU0)`
