### ISSUE TITLE
ONNX export failed on ATen operator mv because

### ISSUE THREAD

**Issue by ozgurshn** [jantic/DeOldify#166]
When I try to export Onnx model from Pytorch this error appears.
Colab link is [here](https://colab.research.google.com/drive/1zRUeHSid0PEbZULODFowxOqxc5R6dvja) 

dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(learn.model.cpu(), dummy_input, "colorizer.onnx")

The error is below:

> /content/DeOldify/deoldify/unet.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if ssh != up_out.shape[-2:]:
> /usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:562: UserWarning: ONNX export failed on ATen operator mv because torch.onnx.symbolic_opset9.mv does not exist
>   .format(op_name, opset_version, op_name))

> KeyError                                  Traceback (most recent call last)
> <ipython-input-11-6588fcd71ffa> in <module>()
>       1 dummy_input = torch.randn(1, 3, 224, 224)
>       2 
> ----> 3 torch.onnx.export(learn.model.cpu(), dummy_input, "colorizer.onnx")
> 
> 7 frames
> /usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
>      89         warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
>      90     global _registry
> ---> 91     return _registry[(domain, version)][opname]
> 
> KeyError: 'mv'
>

**Comment by jantic** [comment]
You're in luck.  I've already set up an Onnx export for my unreleased work.  I won't release the entire export but I'll tell you what you need to do.

1.  Remove Spectral Norm after loading the model.  This is an unsupported operator in ONNX, and is probably why you're seeing the error. Here's a code snipped for you- just pass in the model:

`def remove_all_spectral_norm(item):
    if isinstance(item, nn.Module):
        try:
            nn.utils.remove_spectral_norm(item)
        except Exception:
            pass
        
        for child in item.children():  
            remove_all_spectral_norm(child)

    if isinstance(item, nn.ModuleList):
        for module in item:
            remove_all_spectral_norm(module)

    if isinstance(item, nn.Sequential):
        modules = item.children()
        for module in modules:
            remove_all_spectral_norm(module)`

Full list of supported Onnx operators are here:
https://github.com/onnx/onnx/blob/master/docs/Operators.md

2. If that still doesn't work, you may need the latest PyTorch (not sure on this). They've made quite a few updates to Onnx export suport lately. This will cause problems with the DeOldify however (not 100% compatible) so you may need to make a separate Conda environment to make this convenient and not interfere with your working DeOldify for training/etc.

3.  Keep in mind that if you're looking to export this Onnx model to something else like CoreML, you're bound to run into problems there as well.  I'd only recommend trying to target iOS 13 in that case.  Tensorflow? That's going to be tough too from the looks of it (haven't dug too deep but I know there's unnecessary difficulties).

**Comment by ozgurshn** [comment]
Thanks for the fast response @jantic. Yes, I am planning to convert to CoreML. I will try and give feedback.

**Comment by Sxela** [comment]
Awesome! Will post it in a duplicate thread to help others.

**Comment by Hapsidra** [comment]
> Thanks for the fast response @jantic. Yes, I am planning to convert to CoreML. I will try and give feedback.

Hi, have you converted onnx to CoreML?

**Comment by ozgurshn** [comment]
No, I haven't converted yet @Hapsidra.

**Comment by jantic** [comment]
@Hapsidra  I've converted Onnx to CoreML. It required customization of the Onnx to CoreML script from Apple and a bit of trial and error (this was back in Fall 2019- things may have changed since then).  The customization was required because basically the original conversion script code had a lot of bugs, basically.

**Comment by Hapsidra** [comment]
@jantic can you share your CoreML model or your solution? I got a strange error while trying to convert. Here's my code https://colab.research.google.com/drive/12f9aBzJQqGEr53gVdpFJvuAkWXpJmSzS

**Comment by jantic** [comment]
@Hapsidra  So it looks like the conversion scripts basically have the same problems that I had 6 months ago when I had to modify them to work. 

Unfortunately the work I did is for our commercial efforts here at DeOldify and is a competitive advantage.  So we're not going to release it anytime soon.  The other key thing that I haven't mentioned yet but perhaps it'll save you a lot of time/headache:  You can't run the open source DeOldify on mobile, practically speaking. You have to do a lot of optimizations on the model first.  So when I say I got DeOldify running on iPhone 6s, this entailed a lot of model rework to get it efficient enough. We're talking pretty dramatic levels of optimization here.

What I can tell you about making the conversion scripts work is that it takes a lot of debugging and trial/error, and recognizing that the scripts are making all sorts of wrong assumptions about what models consist of.

**Comment by CNugteren** [comment]
I'm also trying to export this model to ONNX, just to run it later on the same machine with [onnxruntime](https://github.com/Microsoft/onnxruntime), inspired by this [PyTorch superresolution tutorial](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html). Although I could export the model, I couldn't get the same results out: results are completely different.

Here's the most important part of my little script, [full 60-line code with failing test attached](https://github.com/jantic/DeOldify/files/4474350/export_to_onnx.zip):
```python
torch_model = deoldify.generators.gen_inference_wide(
    root_folder=Path("./"), weights_name="ColorizeStable_gen"
).model
torch_model.eval()

example_input_t = torch.rand(1, 3, 96, 96)
torch_output_t = torch_model(example_input_t)

remove_all_spectral_norm(torch_model)    # function posted above by 'jantic'
torch.onnx.export(torch_model, example_input_t, "deoldify.onnx",
                  export_params=True, opset_version=9,
                  do_constant_folding=True, input_names=["input"],
                  output_names=["output"])
```

Any hints where the problem might be? Is it in the size-based conditional interpolation? I guess that would only yield issues if I try different input sizes, but I'm running both the original model and the ONNX model with the same input. I'm assuming here I don't have to retrain the network if I remove the spectral norm as suggested above for inference?

**Comment by jantic** [comment]
There's a few things to point out here.

First, you'll need to do normalization/denormalization somewhere.  My guess is that this is what you are missing.  That is to say- you can't just plug in an image to the model and get the expected result out- there's preprocessing and postprocessing to do.

To make that part easy for you, here's the code I've used to bake that in to the Onnx model itself:

```python
norm, denorm = normalize_funcs(*imagenet_stats)

class ImageScaleInput(nn.Module):
    def __init__(self): 
        super().__init__()
        self.norm = norm

    def forward(self, x): 
        out = (x.div(255.0)).type(torch.float32)
        out,_ = self.norm((out,out), do_x=True)
        return out

class ImageScaleOutput(nn.Module):
    def __init__(self): 
        super().__init__()
        self.denorm = denorm

    def forward(self, x):
        out = self.denorm(x, do_x=True)
        out = out.float().clamp(min=0,max=1) 
        out = self.denorm(out, do_x=False)
        out = (out.mul(255.0)).type(torch.float32)
        return out
```
You then sandwich your model with these, where initial_pytorch_model is the PyTorch model you have currently in your example:

```python
final_torch_model = nn.Sequential(ImageScaleInput(), torch_model, ImageScaleOutput())
```

Finally, note that there's significant steps done in filters.py via ColorizerFilter, which wraps the model, that you'll want to replicate somehow. Namely two big things are happening:

1. Before being put in the model, images are shrunken to a square, with dimensions in pixels being a multiple of 16 times the "render_factor" supplied. This can be thought of as another normalization step in a sense, in that it's making the images more like training. 
2. After going through the model, the model rendered image's "chroma" component is mapped back to the luminescence portion of the original HD image. The end result is a full resolution color rendering that most viewers can't tell was rendered at a much lower resolution.  This is "chroma-subsampling" and it's a key optimization.  You can't get HD images otherwise.

**Comment by CNugteren** [comment]
Thank you for your elaborate response, but I don't think that helps me. I did originally run an image through squaring/unsquaring, with (de)normalisation and the other steps you mentioned, then tried to export the model itself to ONNX, failed, tried to reduce the problem to just the model itself. That's why my code is simplified, to pinpoint the problem.

If you take a look at the code I included in my previous message, you'll see that I run the model twice with some random squared input: once through Torch, and once with ONNX. The results are not the same at all afterwards. Everything you say shouldn't matter for this test, at least as in both cases everything is the same. I've also ran the exported with `verbose=True` and inspected some parts of the network, and they did make sense to me (e.g. it ends with a softmax and then a re-scaling into the -3/+3 range).

**Comment by jantic** [comment]
@CNugteren  ok I don't think I can help you then.  This appears to be an issue to debug on your end. I can just tell you I've exported this model via ONNX before and it works.

**Comment by jantic** [comment]
@CNugteren I did a double check and there is one thing sticking out that's different that you're doing from what I'm doing in my Onnx export.  And that is you're setting  do_constant_folding=True .  I set it to False. That looks like a potentially suspect operation.

**Comment by CNugteren** [comment]
Thanks, but that doesn't help. I also got notified by someone else that they experience the same issue. Shall I open a new issue since it is not really the same as the original? For completeness, these are the steps I take:
```
    git clone https://github.com/jantic/DeOldify.git
    cd DeOldify
    pip install onnx onnxruntime
    pip install -r requirements.txt
    mkdir -p models
    cd models && wget https://www.dropbox.com/s/mwjep3vyqk5mkjc/ColorizeStable_gen.pth?dl=1 && cd ..
    python export_to_onnx.py  # the file attached in one of my earlier comments
```

Some things I've tried also today:
* Run with ` do_constant_folding=False`, no change, just warning messages appearing.
* Run on a different machine, this time with a CUDA GPU available, no change.
* Run with an old commit, e01dd6b4cdc11f512e319e090604b81d4860a948 (2-okt-2019), still failing.
* Try to run with TF-ONNX as inference engine, but that resulted in a lot of error messages from that runtime.

**Comment by jantic** [comment]
@CNugteren  You're on your own on this unfortunately.  It's outside the scope of the project and I won't be digging into this any further. It's something we have working on our end for our commercial efforts but don't plan on making open source.

**Comment by CNugteren** [comment]
OK, I understand, hopefully someone in the community can help :-) Perhaps you could still share with us with what ONNX inference engine(s) you have made it work, e.g. did you also try `onnxruntime`? And if you have a few minutes, could you confirm that my code (see above for the exact steps I took) also fails the assert-all-equal for you? That might hint at whether this is a system/setup/version issue or rather an issue with my/your code.

**Comment by jantic** [comment]
@CNugteren The only other thing I can tell you that might be helpful is that I just went from ONNX directly to CoreML and it worked. That was the only motivating factor to using it- as stepping stone towards CoreML.  I didn't use any runtime like that. Perhaps that wasn't the most methodical thing to do but hey...it worked. 

Question:
> And if you or someone else has a few minutes, could you confirm that my code (see above for the exact steps I took) also fails the assert-all-equal for you? 

Already Answered:
>  I won't be digging into this any further.

**Comment by KeepGoing2019HaHa** [comment]
Convert deoldify to ONNX and NCNN successfully, you can have a look at https://github.com/KeepGoing2019HaHa/AI-application/tree/master/deoldify/ncnn
