### ISSUE TITLE
Idea for training 

### ISSUE THREAD

**Issue by ToukoA** [jantic/DeOldify#174]
In black and white photography its quite typical to use colour filters in order to get the colors & contrasts to pop up in B&W in a desired way. This lead me to thinking that would it be possible / worthwile to train the model to pick up which of the most common filters was used and then to have trained models for the appropriate filter? 

So basically doing the b&w conversion for training using "no-filter", "yellow-filter", "red-filter", "blue-filter", "orange-filter", "green-filter". [More info on the filters from Ilford.](https://www.ilfordphoto.com/colour-filters/?___store=ilford_brochure&___from_store=ilford_brochure) The Cambridge in colour site has [a nice example on how different the photos look with different filters/conversion](https://www.cambridgeincolour.com/tutorials/color-black-white.htm).

It might lead somewhere regarding for example the blue-clothes-preference?

**Comment by ToukoA** [comment]
I dug in to this a bit more. Currently the function for creating training images uses the PIL convert function. 

```
def create_training_images(fn,i):
    dest = path_lr/fn.relative_to(path_hr)
    dest.parent.mkdir(parents=True, exist_ok=True)
    img = PIL.Image.open(fn).convert('LA').convert('RGB')
    img.save(dest)  
```

The PIL convert function converts RGB image to grayscale pixel by pixel using a so-called "ITU-R 601-2 luma transform" e.g. converting the RGB values into greyscale value with the formula 0.299*R+0.587*G+0.114*B. These weights have been designed to produce a nice looking grayscale conversion in standard use.

However, in black and white photography, the weights are probably different to begin with because of how the film chemistries. Adding to this, the most drastic difference to the weights comes when the photographer uses color filters in front of the camera. With a red filter, you would do the transform to grayscale  using only the red channel value, omitting the green and blue altogether, as these colors would not have gone past the red filter onto the film. Similarly with a yellow filter,  you would take the red and green channels: 0.5*R+0.5*G and omit the blue. And so on for the different filters.  So in order to test this idea, a more versatile convert function is needed.

**Comment by jantic** [comment]
These are great points, for sure, and I've had other photographers point out this same thing. I've considered it quite a bit.  This would be an interesting project as a fork of DeOldify (go for it!) but I wouldn't want to design DeOldify around it.  Why?  Because it makes the usage a lot more complicated- most people simply aren't going to know which model to use because either they won't know the specifics of the photo (how it was taken), or they'll simply find the extra step annoying (I would, honestly). My ideal with DeOldify is to keep it super simple:  B&W photo comes in and color photo comes out.  No manual intervention (including getting rid of render_factor once and for all).  What you're describing strikes me more as a "prosumer" type of thing.  I'm sure there's people who want this so I fully encourage you to try it. But it is beyond the scope of DeOldify I think.
