### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by punitvara** [jantic/DeOldify#176]
File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 155, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\test\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 135, in _cuda_deserialize
    return storage_type(obj.size())
RuntimeError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 2.00 GiB total capacity; 1.26 GiB already allocated; 165.43 MiB free; 19.15 MiB cached)

I have 1 TB SSD and 2 GB Nvidia graphics still getting this error. Running this model on windows 10. I have seen reducing batch size may work but don't know where to change batch size. Any body can help ?

**Comment by jantic** [comment]
So...Windows 10 really isn't supported explicitly for DeOldify so any bugs you run into are beyond the scope of what we're willing to hunt down and deal with at this stage (it's just a matter of resources/practicality really).

Second- 2 GB GPU just isn't going to work for DeOldify. That's too little and that's why you'll be getting a CUDA out of memory error.

What I'd recommend, if your interest is simply colorizing images, is to use the Colab, which takes care of all these issues for you! 

https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb
