### ISSUE TITLE
The last part error " Your validation set is empty"

### ISSUE THREAD

**Issue by UserJTZhang** [jantic/DeOldify#178]
Thank you very much for your answer. Now I have solved this problem under windows, changed the parameters of BS and SZ, changed the first one to BS = 32 SZ = 32, later to BS = 20 SZ = 64, BS = 2 SZ = 128. And the following save generated images are changed to BS = 1 Sz = 96.

But when I ran to the last part, the following error occurred. Why can't it find val.

![image](https://user-images.githubusercontent.com/45026028/70401577-42a2a680-1a6b-11ea-98a6-eb0da7af4ea4.png)

![image](https://user-images.githubusercontent.com/45026028/70401480-bc866000-1a6a-11ea-846d-38751bc68ac0.png)

And I don't know if the change of SZ will affect the effect of the model. Do you need to run code of different pixels? Which is the key part of the code? 

Thank you and your team for your input and contribution to this project. I hope to get your answer.

**Comment by jantic** [comment]
I really don't think you should alter the sz parameters like that. If I remember correctly, 32 is too small and will cause an error when you try running it through the model because it can't reduce the image through all the layers (the image size gets halved many times in this process).

But besides that, what you're really asking about here is debugging a problem on your local for Windows that's again beyond the scope of what we're willing to deal with here. There's a number of reasons you could be running into that issue where it's not finding the val folder (missing? permissions not sufficient? etc). 

Anyway, it's one thing to be asked to deal with a bug in a typical install of DeOldify but that's not what you're asking for here.  You're basically asking for tech support, for free, on something you decided to try that we're not recommending. That's not what we're here for. 

So I'm going to leave it at that and hopefully you'll be able to resolve this.

**Comment by UserJTZhang** [comment]
Thank you very much for all you have done. Due to the limited experimental conditions, I can only do this. Because it is remote, there is no way to change windows to Linux.

 I also hope to follow the method you provided as much as possible, but I'm sorry that I didn't do it due to objective conditions, and I hope you can forgive me.

Thank you and your team at one time.
