### ISSUE TITLE
Can someone make a gui windows version

### ISSUE THREAD

**Issue by shadowzoom** [jantic/DeOldify#193]
That would be good af

**Comment by shadowzoom** [comment]
Donation will be raised by 500-100% because not every human know what is hack is python etc

**Comment by alexandrevicenzi** [comment]
@shadowzoom You can run the jupyter notebook in Colab, it does not require any knowledge in Python and is cross-platform. There's even an [Android version](https://play.google.com/store/apps/details?id=ml.colorize.app&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) app based on DeOldify.

If you are willing to send a donation I would happily implement a windows, linux, and os x desktop app.

**Comment by hammerheaddown** [comment]
how much donation for a win desktop version for video?

**Comment by alexandrevicenzi** [comment]
@hammerheaddown Windows support is not planned, you would have better luck hiring a developer to implement the app for you.

@jantic are you aware of any "free" apps for Windows already?

**Comment by jantic** [comment]
@alexandrevicenzi  Thanks- that's well put.  

I'm not aware of any "free" apps for Windows, and putting free in quotes there is quite appropriate because it's certainly not free to develop! I can tell you guys this much:  We've even looked at doing a commercial desktop version just for our proprietary (much better) image models, and we've decided to shelve that for now because it's just too much of a technical challenge currently.  Mostly that has to do with the fact that we're talking about rather large models, and that the support in PyTorch on the C++ end is just very lacking quite frankly.  

Believe me, I've tried.  I have the code in our private repo that I put quite a bit of work into.

And if anybody thinks I'm full of shit they can go right ahead and prove me wrong by making it themselves!

**Comment by alexandrevicenzi** [comment]
I think that the most feasible option would be something like [MyHeritage](https://www.myheritage.com/incolor), but for video.

**Comment by Archviz360** [comment]
a desktop version would be perfect since I have difficulty getting it to work. i started a few weeks ago to try getting deoldiy working on windows using jupyter notebook. I managed to get it connected to the local machine once but never managed to install the required files. since my pc doesn't have a petabyte or terabyte harddrive I found it frustrating having to install large software and learning a coding language i can't remember even a single hour. for me a desktop app would be appreciated and i would even pay for it. so please bring a window ui verson.

**Comment by alexandrevicenzi** [comment]
@Archviz360 as already mentioned, there's a [website](https://www.myheritage.com/incolor) and an [Android/iPhone app](https://www.colorizeimages.com/) ready for use, you can use the website in Windows or install the app on your phone.

**Comment by jantic** [comment]
There's now a Windows GUI version, courtesy of ColorSoft- [https://github.com/ColorfulSoft/DeOldify.NET](https://github.com/ColorfulSoft/DeOldify.NET)

It works!  Even without a GPU.
