### ISSUE TITLE
Usage howto

### ISSUE THREAD

**Issue by avaika** [jantic/DeOldify#2]
Can you please add a small howto in README.md on how to use DeOldify on own set of images? It's not that obvious :)

**Comment by jantic** [comment]
I've added the "For those wanting to start transforming their own images right away" section.  Hopefully this clarifies things!  tl;dr:  I didn't upload weights yet but they're coming soon.  Until you have weights you'd have to train it yourself.  Sorry!  I wanted to get this out as soon as possible because I was just that excited...and I didn't expect - this- much interest.
