### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by alexku44** [jantic/DeOldify#202]
I welcome how to achieve batch image processing. not one at a time?

**Comment by jantic** [comment]
If you're asking for this functionality in a Colab or easy to use UI:  This is well beyond what we're willing to support for free.  It introduces way too much complication and potential for confusion relative to the number of users who actually want it.

If you're asking for a Jupyter notebook: This is one of those things that I do actually use internally for myself in our own DeOldify business efforts.  So I have batch processing notebooks but I haven't open sourced them because they're not coded to be robust enough to be more general use.  It's just enough for us to use for our own purposes. And going beyond that is just something we're not willing to put time into yet with all the other things we have going on right now. 

If somebody else wants to take a stab at it- great!

**Comment by 0xhua** [comment]
> If you're asking for this functionality in a Colab or easy to use UI: This is well beyond what we're willing to support for free. It introduces way too much complication and potential for confusion relative to the number of users who actually want it.
> 
> If you're asking for a Jupyter notebook: This is one of those things that I do actually use internally for myself in our own DeOldify business efforts. So I have batch processing notebooks but I haven't open sourced them because they're not coded to be robust enough to be more general use. It's just enough for us to use for our own purposes. And going beyond that is just something we're not willing to put time into yet with all the other things we have going on right now.
> 
> If somebody else wants to take a stab at it- great!

what is ui sir?

**Comment by jantic** [comment]
UI just means user interface.
