### ISSUE TITLE
How to use DeOldify on Android ?

### ISSUE THREAD

**Issue by abanoub-hanna** [jantic/DeOldify#210]
Is there any tutorials, documentation, or tips for using DeOldify for Android ?

**Comment by jantic** [comment]
This is a bit of a vague question.  I assume you mean to port the model to run natively on Android much like I've done for CoreML on iOS?  If so- I don't have anything for you- haven't done it myself! But I can tell you this much- you can't just port the model as is.  It takes a lot of optimization work and that amounted to about 6 months of research on my end.  And I haven't released that work nor will I for some time because it's something we are probably commercializing.

If you're talking about strictly using DeOldify on an existing app on Android-sure.  The very best version of DeOldify is on the [MyHeritage app](https://play.google.com/store/apps/details?id=air.com.myheritage.mobile&hl=en_US) .  Note that the colorization functionality requires a MyHeritage Complete subscription but they are offering unlimited colorization for free until April 22nd.

Then there's the less expensive option that runs a modified version of the open source DeOldify, [Colorize Images](https://play.google.com/store/apps/details?id=ml.colorize.app&hl=en_US).

**Comment by kirkgutierrdd** [comment]
Yay another software that being monetize to its last grain wouldnt care to pay to have a better dataset 
but it could make old movies so great!
all we got is MyHeritage and yet we cant use it for movies

**Comment by jantic** [comment]
@kirkgutierrdd I suppose you'll be our wealthy patron and pay for mine and Dana's bills then, so that we can give almost two years of work away for free and take care of some hefty hardware expenses? We'll take it! If that's not what you're suggesting, then I'm afraid we'll have to charge money for some of the work we do. And we're not going to apologize for that.
