### ISSUE TITLE
Can we make use of google.colab.files ?

### ISSUE THREAD

**Issue by kirkgutierrdd** [jantic/DeOldify#212]
I really want to upload files from my pc to colab since it would be neet to upload videos/picture/porn-I-guess from your pc 
```
from google.colab import files
uploaded = files.upload()
and then some how to inset to the thing..
```

**Comment by jantic** [comment]
We've already gone down this route before with the first iteration of DeOldify way back in late 2018.  The problem was that it introduced too much complication in terms of things going wrong and wound up causing a lot of problems for users who aren't entirely comfortable with Python code. For that reason we stuck with web hosted images/videos as the only way to work with Colabs for the redesign that followed.

The good news is that you can upload local files to places like Imgur or YouTube, and then use the Colabs as usual.
