### ISSUE TITLE
Commit training output in notebooks

### ISSUE THREAD

**Issue by Aspie96** [jantic/DeOldify#218]
The notebooks are shared without output.
Would you mind sharing an already runned version, insead? This way one can study the notebook even without running it and it's a more efficent use of resources.

**Comment by jantic** [comment]
So I do like this idea in some sense but the thing is, it takes up a lot of extra space in GitHub with the images, and they have a strict limit on commits for that before you have to use GitLFS. Which costs an arm and a leg when you have a popular repo.  I learned that the hard way.  

So I'm not sure this is doable. If you mean just the training notebooks and not the Colabs then that would be much more doable I think. 

But also- there is the [W&B report page](https://app.wandb.ai/borisd13/DeOldify/reports/DeOldify--Vmlldzo0NDU3OA) and corresponding [training notebook]j(https://github.com/jantic/DeOldify/blob/master/ColorizeTrainingWandb.ipynb)- did you see these? 

I'll keep this issue open for now as I may be trying a new training run soon on better hardware, so that the notebook outputs can be generated (assuming that's what you're really looking for).

**Comment by 453trfge543** [comment]
> So I do like this idea in some sense but the thing is, it takes up a lot of extra space in GitHub with the images, and they have a strict limit on commits for that before you have to use GitLFS. Which costs an arm and a leg when you have a popular repo. I learned that the hard way.
> 
> So I'm not sure this is doable. If you mean just the training notebooks and not the Colabs then that would be much more doable I think.
> 
> But also- there is the [W&B report page](https://app.wandb.ai/borisd13/DeOldify/reports/DeOldify--Vmlldzo0NDU3OA) and corresponding [training notebook]j(https://github.com/jantic/DeOldify/blob/master/ColorizeTrainingWandb.ipynb)- did you see these?
> 
> I'll keep this issue open for now as I may be trying a new training run soon on better hardware, so that the notebook outputs can be generated (assuming that's what you're really looking for).

Is there any way I can donate money for training if you ever do it ?

**Comment by jantic** [comment]
Closing. The W&B report page should be sufficient.
