### ISSUE TITLE
Simple Deployment to Production Guide (Inference)

### ISSUE THREAD

**Issue by AshleyRudland** [jantic/DeOldify#219]
Hi @jantic! Thanks ever so much for your repo, me and my business partner have just finished Part 1 of FastAI and we've learnt loads studying the code base. UNETs are bloody amazing, not just for this but many other applications (we think!).

We've been trying for 5 days to get this running in the cloud but failing. We've tried raw VMs on GCP and Google App Engine (running the Dockerfile-api) with no luck. I'm getting in touch to see if you can point us in the right direction.

Two questions:

1. Which platforms are the simplest to get inference running?
1. We ideally want to run it in CPU mode so we've hacked the code base a bit, it's working locally on our machines in CPU mode, but we can't get it running. Do you see any issues with this approach?

**Comment by jantic** [comment]
@AshleyRudland Thanks!

So on production inference:  That's a really tricky question.  Basically I looked into it a while ago and your options get really limited (and expensive) when doing big models like this. Last time I looked doing [elastic inference on Amazon's sagemaker](https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html) looked most appealing terms of cost and scaling, but getting PyTorch models ported to it looked like a huge challenge. But just 5 days ago, this came out:  [Introducing TorchServe: a PyTorch model serving framework](https://aws.amazon.com/about-aws/whats-new/2020/04/introducing-torchserve/) .  I haven't dug deep but that might be the answer to the difficulties I saw previously.

That all being said, what we wound up concluding is that we thought the problem was just to damn hard, risky, and expensive for the two of us bootstrapping a startup to take on.  So we opted to not do it, and instead focused on developing locally executed models on iOS (CoreML) and perhaps desktop.  Note that this required a lot of additional work on optimizing the models and coming up with pretty radically new designs. The thinking behind that is expanded upon in [this Tweet thread.] (https://twitter.com/citnaj/status/1248057682319134720)

What we wound up making a business out of is just focusing on the core model technology and outsourcing the difficulty of figuring out the production deployment to our licensee (a much bigger company that's well equipped for it).

So really if you want to ask about deployment of the open source model on a server, I don't really have satisfactory answers. The Dockerfile-api was created by @jqueguiner and they deployed that at his company, so he may be better able to help you out on questions regarding that.

In terms of running it on CPU mode- Did you see that I recently added [a toggle for CPU mode?](https://github.com/jantic/DeOldify/commit/e55c1abc86475a9a840ae2868a473e6e9779a393)  Do you have the most recent DeOldify? That being said- it's very slow to run it on CPU even with a 16 core ThreadRipper. Not sure that would be acceptable.

**Comment by AshleyRudland** [comment]
Thanks so much @jantic - that's really really helpful!
