### ISSUE TITLE
Transfer learning with your models?

### ISSUE THREAD

**Issue by q5sys** [jantic/DeOldify#221]
This is not an issue with DeOldify, it's a question about using your models.

I'm doing some volunteer archival work for my local Historical Society, and had an idea the other day when I learned about your work.
Instead of training my own model from scratch, I'm wondering how difficult it would be to do transfer learning by taking your models and using my own datasets.  From the archival work I've done, I have a bunch of very old photographs (late 1800s) of buildings that are still standing.  So I was considering going and taking a ton of brand new photos of the buildings today, to train a model specifically for being able to colorize historical photos of that building. 
I know it wont help for de-oldify-ing other pictures, but it seems to me (perhaps I'm wrong) it could give better results since its specifically trained for photos of those buildings. 
My question is, that the writups I've read about doing transfer learning all seem to focus on image recognition models.  I'm curious if the same process of using Keras (as described here: https://machinelearningmastery.com/how-to-use-transfer-learning-when-developing-convolutional-neural-network-models/ ) would work with your pre-trained models? 

To be clear, Im *not* asking you to tell me how to do it, or give me a step by step walk through.  But from your experience I'm hoping you would be able to let me know if you think it would or wouldn't work.

**Comment by jantic** [comment]
@q5sys - I've actually even gone a step further and done transfer learning going from colorization to superresolution and defade models.  I've used both the pretrained generator and critic in this manner- it works! So in my mind it follows that you should be able to do this quite naturally. 

But as far as the data is concerned- I can tell you this much: It seems I got a big boost in ability to deal with buildings generally with incorporating a subset of the open images dataset (didn't use this for this open source version). So that may be another source to consider in addition to what you have, depending on just how much data you have.
