### ISSUE TITLE
deoldify_api  doesn't work

### ISSUE THREAD

**Issue by yunnian** [jantic/DeOldify#224]
docker can run ,but doesn't work
![image](https://user-images.githubusercontent.com/5779513/81138796-d4b8c780-8f95-11ea-847f-e6a9a5e36617.png)
![image](https://user-images.githubusercontent.com/5779513/81137611-f57f1e00-8f91-11ea-9bee-2b38b663cb55.png)
I entered the container and found that there was no relevant process 
so I try the command 'python3 app.py'  ，begin Download :
![image](https://user-images.githubusercontent.com/5779513/81138323-3f690380-8f94-11ea-9e59-4b472650e1a1.png)
then :
![image](https://user-images.githubusercontent.com/5779513/81140418-d5545c80-8f9b-11ea-9887-b24c8a2027c5.png)

 How to make it  run  ?

**Comment by tedbarne** [comment]
If your trying just to get it working here is it
https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb

So here is a tip just abuse https://myheritage.co.il/incolor/ function
make sure to upload a picture to there and then let it ask you to sign in and sign in from the incolor page eitherwise its hard to sign in

**Comment by yunnian** [comment]
> If your trying just to get it working here is it
> https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb
> 
> So here is a tip just abuse https://myheritage.co.il/incolor/ function
> make sure to upload a picture to there and then let it ask you to sign in and sign in from the incolor page eitherwise its hard to sign in

I want to use docker to run stably. I have my own GPU machine，Want it  to run stably as a service.

**Comment by jantic** [comment]
It looks like the artistic model isn't being downloaded successfully from Dropbox  [(link)](https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0) ).  That would indicate I think a network issue on your end.  It'd be worth trying to download from that link I just provided and see what happens.  

Like try this in the terminal:

`wget https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl`

And see how big the file winds up being. If it's 0 kb then you definitely know it's not downloading correctly of course, and it's probably a local network issue because it works fine elsewhere.  It could have also been a temporary issue and it might "resolve itself" if you try again now.

**Comment by yunnian** [comment]
Thank you very much for solving my problem. It's true. I built a docker on the VPN machine and exported it for network reasons, Then loaded it on the GPU machine. But because the GPU machine can't climb over the wall, it can't run. Now I put this file in the docker models directory and it run  successfully!

**Comment by jantic** [comment]
@yunnian Awesome.  Glad to help and thanks for the followup.
