### ISSUE TITLE
I save the IPYNB file as a PY file, run it in the CMD window, and it goes wrong.

### ISSUE THREAD

**Issue by heiheiheibj** [jantic/DeOldify#230]
The code works fine in the jupyter and displays the image correctly. I save the IPYNB file as a PY file, run it in the CMD window, and it goes wrong.
The code is the same.
thx ...
jupyter OK
![image](https://user-images.githubusercontent.com/6910198/81713908-0e636400-94a9-11ea-81a1-98e6c977f4cc.png)

cmd error
![image](https://user-images.githubusercontent.com/6910198/81714014-2d61f600-94a9-11ea-99fc-ee0c5a35b79f.png)

**Comment by jantic** [comment]
Well keep in mind you're largely on your own here once you start trying to do stuff that it's outside the scope of the project.  And in this case it's running the code as a .py file in command line, and on Windows.

But it seems like the issue here might simply be that you have gpu memory being taken up by the notebook that you previously ran still, and that would be resolvable by shutting down the notebook. You can verify gpu memory by looking at Windows task manager's "Dedicated GPU Memory" for the GPU. It should be at or near 0 before you start running the code.

**Comment by heiheiheibj** [comment]
Thank you very much.
