### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by thingol8768** [jantic/DeOldify#233]
Would anyone be able to provide (for a donation) a detailed instruction guide on how to install this on a PC running Windows 10x64 (i9-9000 / 64 GB RAM / NVIDIA GTX2060).

I am not a programmer, but would very much like to run this on my own computer. I've installed Anaconda, Python, and looked at the provided instructions and made many attempts....but I cannot see the finish line. Assuming that it will run like it does in the colab, I would also need to know how to input my source file (my guess is that I am not posting a URL at that point), and anything else that may differ from the colab....but again, I am assuming that most of it will be the same. 

If anyone is interested, please contact me: joeluca@gmail.com
Thanks so much.

**Comment by jantic** [comment]
Well unfortunately Windows isn't officially supported by DeOldify, in order to avoid supporting numerous extra issues unique issues that pop up there because Windows just doesn't get as good support as Linux with the libraries.

That being said, I personally won't do a detailed instruction guide because that'll inevitably make for a lot more reported issues that I just don't want to deal with. But I can tell you I regularly run inference doing the same install on Windows 10 as I've done on Linux, as described in the readme.  I believe you that you're having problems but actually digging into what you did differently just isn't something I'm willing to spend time on.  

It's disappointing for people to hear this for sure, but this is me sharing research code so it's not really tailored for non programmers.  It's not meant to be for everyday users really.  That's what other services (like deepai) and MyHeritage are for.

If you really want to press ahead- the path of least resistance is to do a dual boot of Ubuntu 18.04 and follow the installation instructions from there.  That might sound off putting but it's where you'll have much more likelihood of success.

**Comment by mahaveergautamji** [comment]
https://youtu.be/NA0GfR3zwb0?si=7_NQr0SJs7BvMUg4
