### ISSUE TITLE
I have been stuck after using VideoColorizerColab.ipyn

### ISSUE THREAD

**Issue by jinweime** [jantic/DeOldify#235]
[](https://tva1.sinaimg.cn/large/007S8ZIlgy1get29desqqj31ok0om40u.jpg)

**Comment by jinweime** [comment]
https://tva1.sinaimg.cn/large/007S8ZIlgy1get29desqqj31ok0om40u.jpg)

**Comment by jinweime** [comment]
It has been completed, but the interface has not changed

**Comment by jantic** [comment]
There's trouble shooting text in the Colab that directs you where to look. The only thing that has changed since that was written is that the "Files" text became a folder icon.  Looks like this (highlighted in orange there).  Note that I haven't ran this Colab but that's where you'd look for the video once you're done running.  You might  have to hit refresh there too.

![image](https://user-images.githubusercontent.com/179759/82134196-16255000-97aa-11ea-94b3-c3b00d451cdd.png)

Instructions I'm referring to:

![image](https://user-images.githubusercontent.com/179759/82134189-086fca80-97aa-11ea-8eb4-03898e8fd9c1.png)

**Comment by jinweime** [comment]
thank, found my file
