### ISSUE TITLE
Result video is not the same length

### ISSUE THREAD

**Issue by ashtez** [jantic/DeOldify#240]
![DeOldify](https://user-images.githubusercontent.com/7687660/82585235-fae58680-9b95-11ea-880a-d37487c45c63.png)

As you can see in the appended image, the source video is longer than the produced video (Google Colab). 

Plus there is a time shift (same frame, different time).

**Comment by jantic** [comment]
That's really quite odd.... first time I've heard of this sort of thing being reported in a long time.  Can you provide the YouTube video link to reproduce this?

**Comment by ashtez** [comment]
I sent you the link on Jason@deoldify.ai

**Comment by ruevers** [comment]
I am having the same issue, started happening a few days ago, after last 3 weeks had done a lot of videos, more then 50 and no one have this problem, now all videos when completed ok have this length problem and but is more comum now a error and not complete, he show a error of limit of buffer length

**Comment by jantic** [comment]
I wouldn't recommend trying to do more than a length of a minute or two of video on Colabs. They have severe limitations. Beyond that, you'll be much better off doing this on a local install of DeOldify.

I've increased retries to make sure all fragments are downloaded.  It's a possibility that you're running into incomplete videos being stitched together after fragments are skipped due to download failure. (I've been able to reproduce that locally).
