### ISSUE TITLE
why pretrain Critic twice?

### ISSUE THREAD

**Issue by leeqiaogithub** [jantic/DeOldify#254]
I havd trouble when reading code of  ColorizeTrainingWandb.ipynb.
I am so confused of why we pretraining Critic twice. I can not understand the second one in GAN cycle. we already had it pretrained , isn't it?
Any advice will be helpful.

**Comment by jantic** [comment]
@leeqiaogithub They're trained at different sizes: Once at 128px, and potentially multiple times at 192px.  So that's the first thing to be clear on.  The second thing is you can go through the cycle starting at the heading "Repeatable GAN Cycle" more than once- each time you should be incrementing old_checkpoint_num by 1 manually. Upon repetition, the Critic is finetuned further on distinguishing generated images from real images without the use of GAN training simply because it allows for the critic to get really good while avoiding the collateral damage of training as a GAN.  That's the whole point of NoGAN- minimize the GAN part as much as possible.
