### ISSUE TITLE
In what way is the MyHeritage implementation more advanced?

### ISSUE THREAD

**Issue by zhouhana** [jantic/DeOldify#264]
"The most advanced version of DeOldify image colorization is available here, exclusively."

I'm not that fond of the way MyHeritage treats its users or personal data and don't want to upload photos there. Out of curiousity, exactly how is the MyHeritage implementation more advanced? I want to try to use DeOldify outside of MyHeritage, but I also don't want to miss out on "advanced" functionality. Maybe it's worth using the MyHeritage implementation after all?

**Comment by jantic** [comment]
@zhouhana I guess the short answer is that the colorizations look significantly better in every way :).  Unfortunately I can't give you specific details as to what has changed in the models over the past 1 1/2 years since development of the open source version.  I can just say what I've already said publicly:  Attention is greatly improved upon leading to better details/skin, etc; GAN training is no longer used and results are much more stable; And basically the current models are a culmination of two years of staring at comparison images and slowly having correct hunches as to what's actually going on :). Sometimes.  Most of the time I'm just plain wrong. Rinse and repeat.

But you can try for yourself [here](https://www.myheritage.com/incolor) for free over the next month actually (they're running a promotion currently).

We'll continue to provide them with the latest polished models we have. You can see what I've been posting on Twitter in my media posts here as I continue development: https://twitter.com/citnaj/media
