### ISSUE TITLE
Having troubles with RAM during training learn_critic.fit_one_cycle(4, 1e-4)

### ISSUE THREAD

**Issue by AlexanderKozhevin** [jantic/DeOldify#266]
I stocked on one of the latest stages, right before GAN
https://github.com/jantic/DeOldify/blob/master/ColorizeTrainingArtistic.ipynb

```
learn_critic.fit_one_cycle(4, 1e-4)
```
I've 128Gb of RAM and it's all getting filled within 30 min, 
Moreover I've 100GB swap which is getting filled slowly as also. 
I'm using Nvidia 2080TI. 

Is it normal situation?
Did anybody had similar case?

Becasue I tried to train it like 7 times, with no luck of finishing it.

**Comment by jantic** [comment]
@AlexanderKozhevin  That's pretty new to me. I can't go ahead and try to reproduce this myself yet because my GPUs are all occupied currently and will be for the next two weeks. So I guess I have to start with:  Have you changed -anything-?  Just as an example- I can tell you I know the noise augmentation (not used by the critic trainer here by default) has a nasty memory leak and I haven't gotten around updating it yet.  I use something else internally now.

**Comment by AlexanderKozhevin** [comment]
I just moved it to regular python scripts because broweser with jupyter notebook getting broken because of RAM shortage. More or less I was able to complete it.
@jantic Sorry, I've another stupid question. Is there a way to fine-tune neural network. 
I mean there is already great result which you created. 

It it possible just pick a bunch of extra images and fine-tune on them?
If the answer too big, you can give me just general direct to google.

**Comment by jantic** [comment]
@AlexanderKozhevin It really depends on what kind of data you're talking about.  I've actually fine tuned superresolution functionality out of the model but that was using a lot of data in the process. And that consisted of training the both the generator and critic a bit on the pretraining end first- I forgot how much exactly but the point being you didn't have to do nearly as much training there.  Then I did the normal GAN training stage.

If you're talking about a small amount of data (100s to a few 1000s of images) to finetune on- I haven't tried anything like that yet and honestly I just can't say anything other than "try it!"
