### ISSUE TITLE
Video Colorizer not working?

### ISSUE THREAD

**Issue by Derik555** [jantic/DeOldify#286]
Hello, sorry if im being dumb here or something, but every time i try to use the video colorize, i run each cell in order one by one but each time after i run "Colorize!!" "the colorizer = get_video_colorizer()" cell runs into these errors 

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-10-81c07a854ecc> in <module>()
----> 1 colorizer = get_video_colorizer()

5 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    762             "functionality.")
    763 
--> 764     magic_number = pickle_module.load(f, **pickle_load_args)
    765     if magic_number != MAGIC_NUMBER:
    766         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'm'.

I also dont have an option to change the runtime type to Python 3

**Comment by RickHarrisNL** [comment]
@Derik555 I have been using DeOldify for nearly a year now. It is nice that there is a Colabs solution and Jason Antic is doing great stuff, but Colabs is far from perfect. Over time I have ran into many problems. About half of my colorization attempts failed for some reason (too large file, errors, time-out while downloading the result etc.). **Since today I am getting the same error as you: "UnpicklingError: invalid key, 'm'.  I have already written to Jason to inform him about this problem.**
If it doesn't work, there is a fall back by using "PixBim color surprise AI". But then you need to split the footage into png or bmp frames, use their batch photo colorizer and then re-assemble everything into a video. It takes 4 times as long.

**Comment by slp221** [comment]
@Derik555 Having the same issue here as well, today. It appears the Mkdir Models directory isn't loading, and as a result the rest of the process fails.

**Comment by jantic** [comment]
The model links were moved to a new location by DeepAI and they provided the necessary changes to update the links.  I've just now merged them in and thing should be good to go now.
