### ISSUE TITLE
Artistic models not available

### ISSUE THREAD

**Issue by justinphelps** [jantic/DeOldify#294]
The training models have been deleted from https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0  

 ERROR [13/17] RUN wget -O /data/models/ColorizeArtistic_gen.pth https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0                                            1.0s

![image](https://user-images.githubusercontent.com/2535057/100544644-8469c580-3257-11eb-9182-b1bd4c47b1fe.png)

**Comment by jantic** [comment]
Yep that's intentional.  I got booted off of hosting this and the video model on Dropbox because I was getting too many downloads. Thankfully DeepAI is now providing hosting for these links.

So update your links accordingly (documented in the GitHub repo) or pull the latest source code.  The last remaining piece that I just merged in was updates to the links for the Docker code.

One thing I ask particularly of those making services or scripts is please don't keep downloading the same file if you don't need to.  Cache it!
