### ISSUE TITLE
Question: How can I increase color saturation?

### ISSUE THREAD

**Issue by TaktakTaktouk** [jantic/DeOldify#312]
Does anyone here know a trick to increase color saturation to modernize the colors of each frame?

**Comment by jantic** [comment]
@TaktakTaktouk   I'll start with the easiest option that's already built in:  Lower render_factor values tend to not only make the colors more saturated but also more colorful. There's a cost however and that is you tend to get less detail accuracy.

Otherwise, If you literally mean increasing the saturation value of the frames or photos, that would involve code that I don't have built into the open source version currently.  If you're comfortable with Python, you can increase saturation by taking the pil images that result and running this function on them.  A saturation value of 1.1 to 1.3 would be a good start. Note that Image in this case is PIL.Image .  

def saturate(filtered_image:Image, saturation:float)->Image:
    converter = PIL.ImageEnhance.Color(filtered_image)
    filtered_image = converter.enhance(saturation)
    return filtered_image

**Comment by TaktakTaktouk** [comment]
What I noticed is that the grater is the render_factor, the more the colors are saturated
