### ISSUE TITLE
Slow colorization and some images not coloured. 

### ISSUE THREAD

**Issue by srinivas68** [jantic/DeOldify#342]
I used Ubuntu. i5 with 1050i 3gb graphic card . recently formate and installed Deoldify. slow coloring and some images colour missing. even colab also very slow.

usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.

**Comment by jantic** [comment]
If you're getting some images failing to colorize, it's very likely that you're running out of GPU memory with them and you should be seeing a message like this if that's the case:

> Warning: render_factor was set too high, and out of memory error resulted. Returning original image.

3GB is a pretty small amount of GPU memory for this application, unfortunately.  I'd recommend more on the order of 8GB+.

Now as far as being slow on the Colab, you'll want to make sure that the runtime type is set to GPU.  Otherwise, it'll be running on CPU and yeah that'll be slow!

**Comment by srinivas68** [comment]
ok thank you

**Comment by srinivas68** [comment]
Thank you again. Nvidia driver compatibility problem. Replaced 460 server ( proprietary) to 460 ( proprietary, tested). Working great and fast.. thank you
