### ISSUE TITLE
Dictionary File

### ISSUE THREAD

**Issue by deepikagoel1** [jantic/DeOldify#369]
Could you please let me know if any dictionary file exist where we have the model and weights saved?

**Comment by deepikagoel1** [comment]
I am trying to deploy model using streamlit and facing issue

![image](https://user-images.githubusercontent.com/80449168/126910724-ac3760e1-29af-4d7d-b8ea-53439fa808b7.png)

**Comment by deepikagoel1** [comment]
Could you please let me know the what is the path or variable in which coloured image gets saved in your "app.py" file?

**Comment by jantic** [comment]
So I'll replay the sequence of events here so far.  

First this request is made by you:  

> I tried to load the model on streamlit, please help me in doing it as it will be helpful for my research topic but facing some issues with it.

I then answer it with this:

> This request is beyond the scope of what we're supporting for this project. I've never used streamlit and this project wasn't designed with that in mind (not sure what's involved there). But more to the point- it's a personal request for free remote debugging assistance on a specific and unique use case. We just don't do that here.

[Source](https://github.com/jantic/DeOldify/issues/366)

Then you run into a few issues and we see your problem solving process play out in real time as you gradually figure out what you're doing:

[Here](https://github.com/jantic/DeOldify/issues/368)

And then above same thing apparently:

> Could you please let me know if any dictionary file exist where we have the model and weights saved?

The latter of course is part of the readme.

And then you wind up ignoring the first "No" alluded to above on the streamlit thing by this question:

> I am trying to deploy model using streamlit and facing issue?

There's a reason why I'm drawing boundaries here.  You're obviously doing a bunch of things that are outside the normal  use case of DeOldify and I can pretty much guarantee that the problems you've had so far were probably just the natural consequence of trying to do your own project.  It's fine to do your own project! But we're not here as your personal debuggers for the inevitable difficulties that arise. I'm not sure where you're getting this idea that that's what we do but sorry... I'm not particularly found of doing things for free on demand in the middle of the night here on the west coast of the United States because they are "urgent". 

So from here forward, these requests are just going to be ignored and closed ok? 

End of story.

**Comment by jantic** [comment]
I'll refer you to this statement in the readme:  https://github.com/jantic/DeOldify#a-statement-on-open-source-support
