### ISSUE TITLE
using with vmware

### ISSUE THREAD

**Issue by Archviz360** [jantic/DeOldify#372]
Hi! I'm planning to see if it's possible to use this with VMware. is it working?? Has anyone else tested it??

**Comment by jantic** [comment]
I assume you mean VMWare Workstation Pro. I tried looking into this a few years ago because it would have been hella convenient. But it didn't work back then and it appears it still doesn't now.  It's a product distinction- apparently ESXi (never heard of it previously) is what you'd have to use for proper gpu passthrough to do DeOldify model training.

The latest credible discussion I could find on this topic over the past thirty minutes was [here](https://communities.vmware.com/t5/VMware-Workstation-Pro/ML-inside-Workstation-VMs/td-p/2314440) .

l wouldn't 100% take my word for it but that's what I know.
