### ISSUE TITLE
Strategy for training a VHS model

### ISSUE THREAD

**Issue by irthomasthomas** [jantic/DeOldify#373]
Hello, thanks for making this great project.

I was thinking of trying to improve some VHS TV recordings and wondered about the best way to tackle that. My idea is to use movies I have taped from TV as the Training X images, and then use clean HD digital versions for the Training Y images. Do you think that would work well?

Another issue for me is I don't have a GPU right now, so I thinking of using the free google colab gpu instance. Do you know if people are doing that already with this project?

Many thanks

**Comment by jantic** [comment]
That can definitely work at least to a decent degree- I've already done super resolution using the same techniques. But honestly you may be able to get away with not doing the GAN part and just sticking with the generator model you get just training on Feature Loss.  The GAN portion was motivated by wanting to spice up the colors, but here you have a more straightforward target I think. Adding the GAN part might just make it more complicated and perhaps even more unstable than it needs to be.

I say it'll work to a certain degree because without temporal modeling, which DeOldify doesn't have, you're not going to get complete consistency between frames.  I think this will be less noticeable in this application but you'll have to try it to know for sure.

As far as training on a free colab goes- I don't think that's really a feasible option.  I haven't looked into it for a while but last I checked they have it such that it won't be up for more than a few hours-  training took a few days when I did it.   I'm pretty sure getting the amount of data you'll need available on there is going to be a big pain in the butt. Unless I'm lacking imagination on that one (possible..?).  On the plus side, the GPUs have a surprising amount of RAM- I just checked and got 15GB, so that's great because that's more than what I trained on for the open source DeOldify (11GB). 

I'd really really recommend just creating your own local box to do this work on. You don't have to get the latest GPU (they're pricey I know!). I used a 1080TI.  It'll make your life a lot easier to have this.
