### ISSUE TITLE
Pretrained model updates

### ISSUE THREAD

**Issue by tasiotas** [jantic/DeOldify#376]
Hi,

Do you ever update pre trained models?
Or do you know if anyone is hosting alternative models for DeOldify?

I understand colorization results depend of models, and they depend on training material provided.

Thanks

**Comment by jantic** [comment]
@tasiotas There may be updates to the pretrained models in the future but no, they haven't been updated since the last major release in May 2019. There's been plenty of commercial work done since then but by not giving away that work for free I can pay the bills which is nice in the meantime!

I'm not aware of alternative models being hosted for free of DeOldify other than forks to do different things like anime colorization.
