### ISSUE TITLE
Feature: Colorize color-filtered material

### ISSUE THREAD

**Issue by christian2022** [jantic/DeOldify#377]
There is video material recorded by cameras in cars that is being recorded for technical reasons with color filters (e.g. RCCB or RCCC).
So green (and evtl. blue) is missing in the videos.
Can DeOldify be modified or trained for adding the missing green channel?

More details: Tesla's dash cam has four cameras - front, two at the side and one for the rear. The one for the rear has full colors, the others miss green. So for reconstructing or training the missing color, one might make use of information retrieved from the rear camera. But maybe that's not even neccessary.

**Comment by jantic** [comment]
@christian2022  Yes this is certainly doable. You could really just get away with training on a normal dataset like Open Images and knock out the color channels in question with perhaps OpenCV to make the "before" images, and then use the original images as the "after".  That right there alone would probably be the 90% solution. You'd get additional benefits by "crappifying" the images to more closely simulate the kinds of images you'd be dealing with in reality.  We wrote a blog about that general idea [here](https://www.fast.ai/2019/05/03/decrappify/). 

Granted, all this being said, you're not going to get perfect video because it's not going to have explicit temporal modeling constraints (inherent limitation of DeOldify's simplified approach).
