### ISSUE TITLE
Memory leak in the file deoldify/visualize.py

### ISSUE THREAD

**Issue by groowyCZ** [jantic/DeOldify#382]
When using the image api built with the `Docker-api` build script to colorize an album of images I've ran into issue where the `app.py` would start to consume increasingly more memory which resulted in the container being killed.
Investigating the log revealed this warning message: `RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (matplotlib.pyplot.figure) are retained until explicitly closed and may consume too much memory.`
Looking into the code I've found out that the problem is in the `plot_transformed_image` function located in the `deoldify/visualize.py` file which in the `if compare ... else ...` statement calls functions `self._plot_comparison` or `self._plot_solo` (in my case it was the latter as the value of `compare` was always `False`).
These functions create the figures mentioned in the warning above that are troublesome because they are never properly freed from the memory which results in the program consuming increasingly more memory causing the container to be killed when it runs out of memory.
As of right now I've solved this issue by simply commenting out the `if compare ... else ...` statement mentioned above because it doesn't affect my use case but I'd suggest properly freeing the created figures with `plt.close` after they are no longer needed.

**Comment by jantic** [comment]
@groowyCZ  That call where it's plotting to matplotlib simply shouldn't haver been  there- it's totally unnecessary and will just cause problems.  I was waiting for the go-ahead to fix this from the original author since they were going to be directly affected by the change but that was quite a while ago and I haven't heard anything. So I've decided just to go ahead and fix it myself. Honestly too- I don't see any reason why the images should be saving/reading to disk but I'll just keep that in for now to not upset anybody's setup too much.  I may just eventually correct that too.
