### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by FoxTheMad** [jantic/DeOldify#383]
Hi all,

I have an issue with the links I try to enter. Nothing seems to be working. I have tried with Google Drive, Dropbox, and a local cloud service.
To check if it works, I tried a random photo found on Flickr. But even so, I had to share the Embeded link, paste that in notepad, and get only this from there: https://live.staticflickr.com/65535/51507301957_b3b09c7809_k.jpg

I've seen a tutorial on youtibe, where the person is using Dropbox. I looked at the link he got, and it was identical to what I have. Still, mine is not working :(

Can someone please assist?

Thanks

**Comment by FoxTheMad** [comment]
This is what I get:

---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-36-95c6e7dbdd44> in <module>()
      4 
      5 if source_url is not None and source_url !='':
----> 6     image_path = colorizer.plot_transformed_image_from_url(url=source_url, render_factor=render_factor, compare=True, watermarked=watermarked)
      7     show_image_in_notebook(image_path)
      8 else:

2 frames
/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f441149b950>

**Comment by jantic** [comment]
@FoxTheMad None of those sources of images would be expected to work. The URL provided needs to be a direct image link that is public. Dropbox and Google Drive require password access and so you can't provide direct image links to the Colab, as it won't actually be logged into those services. You'd have to provide a direct public image link  from such a service as Imgur or Flickr. 

If you have a link to the tutorial you're referring to that would be interesting to see, but I'd be very surprised that there would be a way to do that.

As far as "local cloud service" I'm not quite sure what you mean by that, but if it's not providing a publicly accessible -direct- image url then the same thing applies here.

Anyway- I'd suggest rather than trying to figure out how to make this work somehow to instead  go with working with what works.  It'll make life easier. That could mean reuploading to public sites just to get the public link, which I've done myself before many times.  I've deliberately limited the scope of what's supported here because, well, I'm lazy, but also because the point is to cololrize and not to make an awesome image downloader.
