### ISSUE TITLE
[W] CommandLine Interface for Colorization with Local installation

### ISSUE THREAD

**Issue by eadmaster** [jantic/DeOldify#389]
is it possible to add a CommandLine Interface for Colorization not requiring docker + an http client?

e.g.: from the shell:
````
$ DeOldifyCLI InputImage.jpg
````

**Comment by jantic** [comment]
I mean this would certainly be possible but it's not on my agenda. This project is strictly about sharing research and others are free to expand upon it to do things like this.  If somebody makes it and it works well I'll certainly throw a link to it in the readme because it'll probably be useful for a few people.
