### ISSUE TITLE
Error start in Windows  environment 

### ISSUE THREAD

**Issue by DimIsaev** [jantic/DeOldify#406]
I start  [local_run.py](https://github.com/harisreedhar/DeOldify/blob/run-local/run_local.py) in windows 

и  get error 
```
Traceback (most recent call last):
  File "e:/MLDev/Colorized/run_local.py", line 132, in <module>
    model = getModel(args)
  File "e:/MLDev/Colorized/run_local.py", line 109, in getModel
    learn = gen_inference_wide(root_folder=root_folder, weights_name='ColorizeStable_gen') 
  File "e:\MLDev\Colorized\deoldify\generators.py", line 19, in gen_inference_wide
    learn.load(weights_name)
  File "E:\MLDev\Colorized\.env\lib\site-packages\fastai\basic_train.py", line 261, in load
    if purge: self.purge(clear_opt=ifnone(with_opt, False))
  File "E:\MLDev\Colorized\.env\lib\site-packages\fastai\basic_train.py", line 301, in purge
    self._test_writeable_path()
  File "E:\MLDev\Colorized\.env\lib\site-packages\fastai\basic_train.py", line 177, in _test_writeable_path   
    raise Exception(f"{e}\nCan't write to '{path}', set `learn.model_dir` attribute in Learner to a full libpath path that is writable") from None
Exception: [Errno 2] No such file or directory: 'models\\tmpa9q0gfvp'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable  
```

how right  write  models  path ?

**Comment by jantic** [comment]
This one has a pretty easy answer: Windows isn't supported.

**Comment by DimIsaev** [comment]
oh dude yes you are a problem solving guru

can write code that will work on different systems?
rather than simple answers...

**Comment by jantic** [comment]
Well, first, go ahead and solve the problem yourself then, if you want to be consistent in your position here.

Second, part of effective problem solving is limiting the scope of problems in the first place. Windows isn't supported because the underlying key libraries didn't support it when I put this up to share the research. And that's all it is. I'm sharing research, not working for free for people who are quick on the trigger to bash the creator on the baseless grounds that they're entitled to it for....reasons.

Now of course I don't expect any of that to change your mind. But I've said my peace and that's that.
