### ISSUE TITLE
Having "bad" result with a photograph, not sure if I'm using it correctly

### ISSUE THREAD

**Issue by arbolis** [jantic/DeOldify#417]
I am trying to colorize the following picture: https://upload.wikimedia.org/wikipedia/commons/e/e9/Solvay_conference_1927_%28group_photograph%29_bw.jpg

Here is the best result I could achieve: https://imgur.com/a/nKmNlbG#x1goy8K, I just used the collab (non artistic) version with a parameter set to 40 (otherwise the colors are too dull and the picture is very similar to the B&W version).

I am aware that a cropped version of this picture is to be found on the web (with lesser resolution I think), I would like this uncropped version, and make a poster out of it, that's why I bother to colorize the picture in the first place.

However, as you can see, the result is "bad", near Einstein and on his right, some faces haven't been colored. On his left, a white beard has been colorized in red. The result is very far from the other online colorized versions of this picture (or a variant of this picture). I am wondering whether I can tweak some other setting(s) than the slide that goes from 7 to 40 on collab. Is there something else I can do to make it better?

**Comment by jantic** [comment]
That's probably about as good as you're going to get with the 3 year old open source model. We have commercial work that we've been feverishly working on since then which at least gets rid of the zombie issues you're citing:  [https://i.imgur.com/NJDaSuR.jpg](https://i.imgur.com/NJDaSuR.jpg) .

But ultimately, you're also dealing with a tech that has severe limitations and I'd still characterize even the latest results as overly dull. You're just not going to get the kind of results that manual colorizers get any time soon with AI.

**Comment by arbolis** [comment]
Thank you very much for the feedback, I didn't even know I was dealing with a 3 years old software. 

Your picture, by the way, is very much better. The building looks duller than in my picture, but the people look OK.
