### ISSUE TITLE
Train your own model

### ISSUE THREAD

**Issue by zeke800** [jantic/DeOldify#418]
Hi! I'm trying to train a model to color black and white satellite images, based on the ColorizeTrainingStable notebook. I am getting the following error: 

![image](https://user-images.githubusercontent.com/82127189/164506151-11200861-5e9a-4802-8eb6-de2c3c35f2c7.png)

How would I go about training my own model, and how can I solve my error?

Thank you so much!

**Comment by johnowhitaker** [comment]
fastai.callbacks is fastai V1, you likely have fastai V2. In V2 you'd likely need something like `from fastai.callback.all import *` but there will sadly be other issues due to all this code being based (afaik, 5 minutes into trying to play with this myself) on version 1 of fast ai.

**Comment by jantic** [comment]
@johnowhitaker  Thanks!  That's exactly right.  @zeke800 You'll need to use the conda install per the readme to keep things straight here with the installation. That's where you will get the correct fastai v1 installation (and everything else). I wouldn't try to diverge from that installation process, and I won't be supporting anything else.

As far the rest of your question goes- installation is the easy part. Asking about how to train the model- well...  the best I can tell you is to just follow the notebooks, and searching the many closed issues here for various questions that have been answered already. Beyond that, if you run into difficulties (you will) you'll have to rely on knowing the ropes of Python, fastai and deep learning in general. It's a vague question to answer because I don't know where you are in terms of knowledge base. But there's no short cuts.
