### ISSUE TITLE
FEATURE: True-Color Determination

### ISSUE THREAD

**Issue by alvinchipmunk** [jantic/DeOldify#428]
**True-Color Determination**

 The feature I propose involves the use of image data and available knowledge of the depicted scene to determine the actual, original colors of historically important objects in the scene. One aspect makes use of the light reflected from one surface onto another. When the color of one surface is known, the possible colors of the other surface can be reduced based on the resultant influence on the grayscale level in the area partially illuminated by that reflected light. My hope, is that with enough determinations of what colors certain surfaces **aren't**, one can determine, through simple logical deduction what the colors of the important objects in the scene **are**.

**Other useful bits of information:**
- The color of the light illuminating each portion of the scene (direct sunlight versus a blue sky, or clouds, and so on...).
- Identities of plants and animals in the scene.
- Weather and climate records for the area.
- Photos of accurate, physical recreations of a scene with objects of various colors tested for comparison.

 I'm aware that this likely appears (and possibly is) far-fetched, but I thought perhaps experts could prove it otherwise. This just might be our last remaining hope of learning such things about the past.

**Comment by jantic** [comment]
I'm back from a big trip in Iceland so apologies for the wait. The thought put into this post is certainly appreciated. but what you're speaking of here is a whole other research project far beyond the scope of the DeOldify project. I can tell you though that the most promising direction to incorporate this sort of information was pioneered by Emil Wallner in this newer project:  https://palette.fm/ .  Simply put- building upon language modeling seems to be the key to getting better results, by incorporating more hard earned human knowledge into building the resulting images. That would cover at least a good portion of what you're referring to there with the "other useful bits of information" and I think that would go quite far. 

As far as the grayscale information- well unfortunately grayscale can represent multiple color solutions. That's one challenge. And while logical deduction sounds sensible and is to a certain extent, it's the actual implementation of how you'd segment and break that problem up which would be the -very- hard part in my opinion. And it'd still ultimately be at best the work of some heuristics and "guesses" due to the grayscale ambiguity problem.

So again- super interesting areas to ponder, but it's definitely a whole other project to tackle all these things. And I think we're just now arriving at potential solutions with the recent multi-modal vision and language modeling stuff that has come out along with diffusion models, etc.
