### ISSUE TITLE
Painful to run on Colab for free

### ISSUE THREAD

**Issue by bitplane** [jantic/DeOldify#431]
The final step combines the download, extract, colourize and combine stages. This means that if you run out of time on Colab you lose everything. You can't easily hack the steps to get around the limits:

* Videos uploaded to Google Drive, you need to wait until they're processed before youtube-dl will download them. You can't easily skip this by sideloading.
* You need to use a GPU instance to download the video and extract the frames, this unnecessary.
* You can't stop the process after N frames, hive them off then continue later.
* If you run out of time before the output video is combined, you lose all your data. Even after every frame has been colourized, you need to start again cause Google crushed your nuts with their dark marketing pattern.

So it'd be much nicer if the steps were split out.

**Comment by pitt6** [comment]
[colabbug1.pdf](https://github.com/jantic/DeOldify/files/9924588/colabbug1.pdf)

Downloads truncating, Reason unknown,  A bug?
[colabbug1.pdf](https://github.com/jantic/DeOldify/files/9924598/colabbug1.pdf)

**Comment by bitplane** [comment]
@pitt6 

> If you run out of time before the output video is combined, you lose all your data. Even after every frame has been colourized, you need to start again cause Google crushed your nuts with their dark marketing pattern

Your colab VM can disappear at any time, so probably got deleted. Move your files to Google Drive and download them from there. Or buy colab access. Or don't, because they'll still delete your files.

**Comment by pitt6** [comment]
I have researched moving files to drive but I find no clear instructions how to do that. I get a log of could not fetch. Greek to me! I was getting downloads of 9 min files. Now i have been shut down totally. No output. They claim it free but you dont get anything. I miss the red colors. But still quite amazing to me.
Thanks for all.

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 4, 2022 at 20:46, Gaz ***@***.***> wrote:   


@pitt6


If you run out of time before the output video is combined, you lose all your data. Even after every frame has been colourized, you need to start again cause Google crushed your nuts with their dark marketing pattern


Your colab VM can disappear at any time, so probably got deleted. Move your files to Google Drive and download them from there. Or buy colab access. Or don't, because they'll still delete your files.

**Comment by pitt6** [comment]
By the way. Seems to be a waste of Computer resources to run for 2 hrs and then another 1 hr for audio then downloading for another then nothing. You start all over again. I suppose the logic was for small files. Then pay for nothing. I have no friends with graphics cards to suite.
Tom

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 5, 2022 at 12:35, Tom ***@***.***> wrote:   I have researched moving files to drive but I find no clear instructions how to do that. I get a log of could not fetch. Greek to me! I was getting downloads of 9 min files. Now i have been shut down totally. No output. They claim it free but you dont get anything. I miss the red colors. But still quite amazing to me.
Thanks for all.

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 4, 2022 at 20:46, Gaz ***@***.***> wrote:   


@pitt6


If you run out of time before the output video is combined, you lose all your data. Even after every frame has been colourized, you need to start again cause Google crushed your nuts with their dark marketing pattern


Your colab VM can disappear at any time, so probably got deleted. Move your files to Google Drive and download them from there. Or buy colab access. Or don't, because they'll still delete your files.

**Comment by pitt6** [comment]
I just noticed, my audio and colorization are completed . Runtime is terminated. You must select output download after colorization icon stops revolving giving time. The icon gives a couple of arrowed circles then it shows yellow progress. Last 4 attemps it has terminated before at the last moment. Jason said there was a workaround in the instructions in the notebook. 
I looked for it but no luck. If you were able to upload to cloud, would you share how?

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 5, 2022 at 12:51, Tom ***@***.***> wrote:   By the way. Seems to be a waste of Computer resources to run for 2 hrs and then another 1 hr for audio then downloading for another then nothing. You start all over again. I suppose the logic was for small files. Then pay for nothing. I have no friends with graphics cards to suite.
Tom

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 5, 2022 at 12:35, Tom ***@***.***> wrote:   I have researched moving files to drive but I find no clear instructions how to do that. I get a log of could not fetch. Greek to me! I was getting downloads of 9 min files. Now i have been shut down totally. No output. They claim it free but you dont get anything. I miss the red colors. But still quite amazing to me.
Thanks for all.

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 4, 2022 at 20:46, Gaz ***@***.***> wrote:   


@pitt6


If you run out of time before the output video is combined, you lose all your data. Even after every frame has been colourized, you need to start again cause Google crushed your nuts with their dark marketing pattern


Your colab VM can disappear at any time, so probably got deleted. Move your files to Google Drive and download them from there. Or buy colab access. Or don't, because they'll still delete your files.

**Comment by bitplane** [comment]
You need to:
* first attach your google drive using the file browser on the left, before you run anything.
* Then you need to run it on a very small file
* Then you need to go to the bottom of the file and write the commands that copies the output video into your Google drive (This is awkward without shell access, which you only get on a paid Colab environment)
* After you've tested that the script works, and your file appears in drive, then you put your big video in and queue up all the steps.
* If you're lucky, it'll run the process, copy the output file to Google Drive, then your VM will get deleted. If you're unlucky it'll delete your VM halfway through.

Yes it's a complete pain. I've got a pull request with some changes in there to make it easier, but it won't magically fix this issue - it'll make it easier to continue if you manually run a backup part-way through and then manually copy the files back in to continue, so you don't have to start again. But I've not supplied those commands as changes to the notebook.

But as it says in the README, this isn't really a polished product for end-users. You need to understand what it's doing, where the files are, how to debug the problems and so on. This is what this issue that you're posting to is about, it's painful to run on colab for free even if you're a developer who knows what they're doing.

That said, your experience with it make me think that it'd be better to just have the "attach google drive" and "copy to drive" steps in there. When I have time I'll add them to my pull request and you can try it out if you like

**Comment by pitt6** [comment]
Yes and yes. I would like the two steps included. 
I dont think even with your instructions i can get there. But very kind of you to reply.
Is attach drive and mount drive the same. I might be able to do that?
But command code to copy file to drive would take a lot of learning.
I tried some right clicks on results where it had an upload arrow. Bombed it good!
Thanks.
Tom




Sent from Yahoo Mail on Android 
 
  On Mon, Nov 7, 2022 at 22:02, Gaz ***@***.***> wrote:   


You need to:
   
   - first attach your google drive using the file browser on the left, before you run anything.
   - Then you need to run it on a very small file
   - Then you need to go to the bottom of the file and write the commands that copies the output video into your Google drive (This is awkward without shell access, which you only get on a paid Colab environment)
   - After you've tested that the script works, and your file appears in drive, then you put your big video in and queue up all the steps.
   - If you're lucky, it'll run the process, copy the output file to Google Drive, then your VM will get deleted. If you're unlucky it'll delete your VM halfway through.

Yes it's a complete pain. I've got a pull request with some changes in there to make it easier, but it won't magically fix this issue - it'll make it easier to continue if you manually run a backup part-way through and then manually copy the files back in to continue, so you don't have to start again. But I've not supplied those commands as changes to the notebook.

But as it says in the README, this isn't really a polished product for end-users. You need to understand what it's doing, where the files are, how to debug the problems and so on. This is what this issue that you're posting to is about, it's painful to run on colab for free even if you're a developer who knows what they're doing.

That said, your experience with it make me think that it'd be better to just have the "attach google drive" and "copy to drive" steps in there. When I have time I'll add them to my pull request and you can try it out if you like

**Comment by pitt6** [comment]
Tried running file at 27 factor versus 31. It was really awful but it gave output. They said 21 is best. Then i will need to go higher factors. Maybe 35?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 8, 2022 at 16:23, Tom ***@***.***> wrote:   Yes and yes. I would like the two steps included. 
I dont think even with your instructions i can get there. But very kind of you to reply.
Is attach drive and mount drive the same. I might be able to do that?
But command code to copy file to drive would take a lot of learning.
I tried some right clicks on results where it had an upload arrow. Bombed it good!
Thanks.
Tom




Sent from Yahoo Mail on Android 
 
  On Mon, Nov 7, 2022 at 22:02, Gaz ***@***.***> wrote:   


You need to:
   
   - first attach your google drive using the file browser on the left, before you run anything.
   - Then you need to run it on a very small file
   - Then you need to go to the bottom of the file and write the commands that copies the output video into your Google drive (This is awkward without shell access, which you only get on a paid Colab environment)
   - After you've tested that the script works, and your file appears in drive, then you put your big video in and queue up all the steps.
   - If you're lucky, it'll run the process, copy the output file to Google Drive, then your VM will get deleted. If you're unlucky it'll delete your VM halfway through.

Yes it's a complete pain. I've got a pull request with some changes in there to make it easier, but it won't magically fix this issue - it'll make it easier to continue if you manually run a backup part-way through and then manually copy the files back in to continue, so you don't have to start again. But I've not supplied those commands as changes to the notebook.

But as it says in the README, this isn't really a polished product for end-users. You need to understand what it's doing, where the files are, how to debug the problems and so on. This is what this issue that you're posting to is about, it's painful to run on colab for free even if you're a developer who knows what they're doing.

That said, your experience with it make me think that it'd be better to just have the "attach google drive" and "copy to drive" steps in there. When I have time I'll add them to my pull request and you can try it out if you like

**Comment by pitt6** [comment]
Hello again:
Waited 2 hrs 45 minutes. I just ask to download and it looked like it was not going to do it. It did not but got details on could not fetch. Meaning it could not find the file to download?
A few days ago i had problem with Google chrome not updated. It was really quick on 4:30 files.But was using Mozzila. 
I am attaching details on could not fetch. Can you tell from this what is happening.
Hope you had a good thanksgiving meal and time.
Tom

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 10, 2022 at 14:22, Tom ***@***.***> wrote:   Tried running file at 27 factor versus 31. It was really awful but it gave output. They said 21 is best. Then i will need to go higher factors. Maybe 35?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 8, 2022 at 16:23, Tom ***@***.***> wrote:   Yes and yes. I would like the two steps included. 
I dont think even with your instructions i can get there. But very kind of you to reply.
Is attach drive and mount drive the same. I might be able to do that?
But command code to copy file to drive would take a lot of learning.
I tried some right clicks on results where it had an upload arrow. Bombed it good!
Thanks.
Tom




Sent from Yahoo Mail on Android 
 
  On Mon, Nov 7, 2022 at 22:02, Gaz ***@***.***> wrote:   


You need to:
   
   - first attach your google drive using the file browser on the left, before you run anything.
   - Then you need to run it on a very small file
   - Then you need to go to the bottom of the file and write the commands that copies the output video into your Google drive (This is awkward without shell access, which you only get on a paid Colab environment)
   - After you've tested that the script works, and your file appears in drive, then you put your big video in and queue up all the steps.
   - If you're lucky, it'll run the process, copy the output file to Google Drive, then your VM will get deleted. If you're unlucky it'll delete your VM halfway through.

Yes it's a complete pain. I've got a pull request with some changes in there to make it easier, but it won't magically fix this issue - it'll make it easier to continue if you manually run a backup part-way through and then manually copy the files back in to continue, so you don't have to start again. But I've not supplied those commands as changes to the notebook.

But as it says in the README, this isn't really a polished product for end-users. You need to understand what it's doing, where the files are, how to debug the problems and so on. This is what this issue that you're posting to is about, it's painful to run on colab for free even if you're a developer who knows what they're doing.

That said, your experience with it make me think that it'd be better to just have the "attach google drive" and "copy to drive" steps in there. When I have time I'll add them to my pull request and you can try it out if you like

**Comment by pitt6** [comment]
Here is attachment!

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 29, 2022 at 3:47, Tom ***@***.***> wrote:   Hello again:
Waited 2 hrs 45 minutes. I just ask to download and it looked like it was not going to do it. It did not but got details on could not fetch. Meaning it could not find the file to download?
A few days ago i had problem with Google chrome not updated. It was really quick on 4:30 files.But was using Mozzila. 
I am attaching details on could not fetch. Can you tell from this what is happening.
Hope you had a good thanksgiving meal and time.
Tom

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 10, 2022 at 14:22, Tom ***@***.***> wrote:   Tried running file at 27 factor versus 31. It was really awful but it gave output. They said 21 is best. Then i will need to go higher factors. Maybe 35?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 8, 2022 at 16:23, Tom ***@***.***> wrote:   Yes and yes. I would like the two steps included. 
I dont think even with your instructions i can get there. But very kind of you to reply.
Is attach drive and mount drive the same. I might be able to do that?
But command code to copy file to drive would take a lot of learning.
I tried some right clicks on results where it had an upload arrow. Bombed it good!
Thanks.
Tom




Sent from Yahoo Mail on Android 
 
  On Mon, Nov 7, 2022 at 22:02, Gaz ***@***.***> wrote:   


You need to:
   
   - first attach your google drive using the file browser on the left, before you run anything.
   - Then you need to run it on a very small file
   - Then you need to go to the bottom of the file and write the commands that copies the output video into your Google drive (This is awkward without shell access, which you only get on a paid Colab environment)
   - After you've tested that the script works, and your file appears in drive, then you put your big video in and queue up all the steps.
   - If you're lucky, it'll run the process, copy the output file to Google Drive, then your VM will get deleted. If you're unlucky it'll delete your VM halfway through.

Yes it's a complete pain. I've got a pull request with some changes in there to make it easier, but it won't magically fix this issue - it'll make it easier to continue if you manually run a backup part-way through and then manually copy the files back in to continue, so you don't have to start again. But I've not supplied those commands as changes to the notebook.

But as it says in the README, this isn't really a polished product for end-users. You need to understand what it's doing, where the files are, how to debug the problems and so on. This is what this issue that you're posting to is about, it's painful to run on colab for free even if you're a developer who knows what they're doing.

That said, your experience with it make me think that it'd be better to just have the "attach google drive" and "copy to drive" steps in there. When I have time I'll add them to my pull request and you can try it out if you like

**Comment by jantic** [comment]
Sorry for the very late response- was very busy the last few months. Unfortunately the free Google Colabs will probably continue to be increasingly nerfed as they move from drawing in users to trying to actually make money. So I'm not inclined to create work arounds for this as it's just research code I'm sharing, and the answer to these problems is to either get the paid version or install locally.
