### ISSUE TITLE
ResolvePackageNotFound cuda90

### ISSUE THREAD

**Issue by ccorcos** [jantic/DeOldify#45]
```
~/C/DeOldify ❯❯❯ conda env create -f environment.yml

Solving environment: failed

ResolvePackageNotFound:
  - cuda90
```

**Comment by ccorcos** [comment]
I'm on MacOS... https://github.com/fastai/fastai/issues/84

Commenting out `#- cuda90` fixed the issue... Will keep you posted on whether the program is able to run.

**Comment by ccorcos** [comment]
Also, I used `brew cask install miniconda` to get conda up and running. I'm assuming not everyone who wants to run this program has conda installed.

**Comment by ccorcos** [comment]
Didn't work 😭 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-b6b2691acef0> in <module>
     20 plt.style.use('dark_background')
     21 torch.backends.cudnn.benchmark=True
---> 22 torch.cuda.set_device(0)

/usr/local/miniconda3/envs/deoldify/lib/python3.6/site-packages/torch/cuda/__init__.py in set_device(device)
    260     """
    261     if device >= 0:
--> 262         torch._C._cuda_setDevice(device)
    263 
    264 

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```

![image](https://user-images.githubusercontent.com/1794527/48985947-a5283f00-f0c2-11e8-8d1f-c60f2c0b04ca.png)

Would be sweet if this were an executable program...

**Comment by jantic** [comment]
> Also, I used `brew cask install miniconda` to get conda up and running. I'm assuming not everyone who wants to run this program has conda installed.

So here's the thing on that- this is  pretty much a one-man show (with some great contributions from others).  And I'm a big believer in being very selective about the problems I'm willing to tackle (because every problem you tackle means something else gets put back in line).

I'm not (yet) in the business of making this project work for -everybody- and everybody's tastes/situation.  I went with Conda with quite frankly, it's simply the best installation choice (compared to PIP), and I'm choosing to go with a single and opinionated installation process to simplify things in terms of support.  Not only because it's easier to maintain one thing instead of two, but I know that there will be more problems with trying to support other options.

Now that being said- this does seem on the surface to contradict my stance that I want to make this project useful/usable on the broad scale.  But to clarify that- I ultimately intend on making this a simple web app/phone app that requires zero technical know-how (but won't be free).  The Colab notebook will still be there though, and that doesn't require much know-how to operate either.

**Comment by jantic** [comment]
From Twitter thread earlier:   Unfortunately MacOS support hasn't been on my radar yet- most of the tools and the community in deep learning is centered around Linux.  So I haven't tried (can't 100% rule it out!).  It looks like a difficult road though.  On the Pytorch site, for example, I see this:

# MacOS Binaries dont support CUDA, install from source if CUDA is needed

I think that's the source of your issue you submitted to Github.  That being said, not sure if you saw that there's a Colab notebook.  If all you want to do is colorize and not train, then I'd say that's the way to go- way easier!

https://colab.research.google.com/github/jantic/DeOldify/blob/master/DeOldify_colab.ipynb

I'm going to close this because MacOS simply isn't advertised to be supported for development, and I need to pick my problems wisely.

**Comment by ccorcos** [comment]
Oh sweet! I didnt realize I could run it online! Thanks you so much for making this @jantic. I just colorized a few old photos of my grandfather. Would it **really** cool if you made a bot that colorized photos on Redit HistoryPorn of TheWayWeWere

![before-after 2](https://user-images.githubusercontent.com/1794527/49059383-7cd13b00-f1bd-11e8-8a5c-85eb5b374c2b.png)
![before-after](https://user-images.githubusercontent.com/1794527/49059384-7cd13b00-f1bd-11e8-9571-57eea55b2f76.png)
![before-after 3](https://user-images.githubusercontent.com/1794527/49059385-7cd13b00-f1bd-11e8-924b-5e9d57239df5.png)

**Comment by jantic** [comment]
> Would it really cool if you made a bot that colorized photos on Redit HistoryPorn of TheWayWeWere

Mayhaps!  That's actually where I've been getting most of my photos....
