### ISSUE TITLE
 Why do we need to unfreeze the learner everytime before  learn.fit_one_cycle() ?

### ISSUE THREAD

**Issue by winnieepooh** [jantic/DeOldify#464]
Why do we need to unfreeze the learner everytime before  learn.fit_one_cycle() ?
when we learn.save() a model, does it freeze it by default?
When we load the saved model, does it does it freeze or unfreeze the model by default?
 
I'm sorry for asking so many questions.I'm looking forward to hearing from your reply.
Thanks!

**Comment by jantic** [comment]
It's been quite a while since I made the decision to explicitly do that. But if I were to guess my exact intentions:  It's two fold:

1. Be explicit about the requirement to unfreeze for each training step for readability and clarity (even if it's technically redundant).
2. Make the code robust to stops/resumes, esp since this is a Jupyter notebook. That is, it's making it so that if you just want to run a subset of cells to get caught up to your checkpoint, the necessary steps are mostly self-contained at the current training step. 

I think that's pretty much it.
