### ISSUE TITLE
DeOldify with Docker for API  and CPU rendering without NVIDIA GPU

### ISSUE THREAD

**Issue by Herzbergh** [jantic/DeOldify#470]
Hey, how can I use DeOldify with Docker for API  like that:

echo "http://$(curl ifconfig.io):5000" && nvidia-docker run --ipc=host -p 5000:5000 -d deoldify_api

curl -X POST "http://MY_SUPER_API_IP:5000/process" -H "accept: image/png" -H "Content-Type: image/jpeg" -F "file=@slave-family-P.jpeg" -F "render_factor=35" --output colorized_image.png

i found that you can choose the render device in a few files e.g:  "#choices:  CPU, GPU0...GPU7\n",
    "device.set(device=DeviceId.CPU)" 

but i can't get working for Docker as API for localfiles with CPU rendering.. its really important for me to get in working! 

Any Idea?

**Comment by jantic** [comment]
The docker functionality isn't supported anymore, chiefly because docker has all sorts of potential support issues. I can tell just looking at this that this is probably a bit of a rabbit hole. Really...your best bet might be to try to get ChatGPT-4 to get you to walk through it. It might take a few back and forths but I've generally had a lot of success with it.
