### ISSUE TITLE
Upload discriminator weights, to allow fine-tune training

### ISSUE THREAD

**Issue by md5wasp** [jantic/DeOldify#53]
Thanks for making this! I had no problems getting it working on Windows 10, and /colou?ri[zs]ing/ some images on my 980Ti.

The image I want to use it for (two boys on a row-boat) doesn't come out great, so I'd love to be able to fine-tune on a bunch of similar images so I can get a good result. You've kindly uploaded the generator weights, but I'd like the discriminator weights too (DCCritic / GANTrainer.netD).

No way I can train this all the way myself on my 980Ti 😅 but maybe just a few more examples is possible...

**Comment by jantic** [comment]
Having pretrained discriminator weights available is the intention, for sure.  I screwed up on my initial commit of this project and only had good generator weights to upload (I was in a hurry).  Ever since, I've been working on improving the model but I won't put up anything until it's solid.  

I'm definitely working on this, and now I have some really really good help on this (will elaborate more later).  But yeah...definitely on the agenda.  Sorry about the wait!  It takes a long ass time to train on my end as well, even with 4 1080TIs....

**Comment by grinvaldsjanis** [comment]
Hello! I tried this stuff in google code/server... amazing, although sometimes it throws out absolutely colourized nonsense. But that's ok.
Tried this photo with Chopin https://twitter.com/StaffGrand/status/1082178202376851462
Is there a plan to make it as an installable app for windows with some user-friendly UI. It took me some time as for artist to figure out what to do with this code, and I am not sure what to do with downloadable stuff at all. Should be some exact instructions on how to get it to work.
Thank You for Your work and the opportunity to try it out!

**Comment by jantic** [comment]
@grinvaldsjanis I do have plans to make this an app eventually.  But I wouldn't expect that for a while yet.  Luckily, there's a website that actually renders using DeOldify that's super easy to use (I didn't make it):

https://colorize.cc/

The server is using a GPU with less memory than ideal so they're not as good as what you can get using a full 11GB+ GPU.  But they're still quite good.

**Comment by jantic** [comment]
@grinvaldsjanis Well...that's the ultimate goal of this project.  I want to make a one stop shop for fixing old photos (de-fading, color correction/colorizing, super-res, etc).  I just haven't gotten to that point yet.  I know other ai implementations have been attempted but I don't know of any that are easily accessible.
