### ISSUE TITLE
how to run the "ColorizeVisualization"

### ISSUE THREAD

**Issue by Hyfred** [jantic/DeOldify#61]
Hello, I am sorry to bother you again. I have tried your case several times, but it still has problems:
My computer environment is win10, cpu. I have seen the cpu implementation you mentioned in the issue. It mentions the modification of the command. But if I follow 'conda env create -f environment.yml' at the beginning, the following error will occur:

![image](https://user-images.githubusercontent.com/38806779/49708881-83a38780-fc6c-11e8-97f7-da60a88c5078.png)

So I tried to download the cpu version of the module such as pytorch. Then tried to use the weight you have given me and run "ColorizeVisualization" directly. But when I load the module, the following problem occurs.

![image](https://user-images.githubusercontent.com/38806779/49709323-b189cb80-fc6e-11e8-99eb-f8a490da3595.png)

Then I found the file "\fastai\torch_imports.py" along the path and saw this syntax error.

![image](https://user-images.githubusercontent.com/38806779/49709361-de3de300-fc6e-11e8-8291-de5eafb8e56d.png)

I have problems loading the module. So python can't continue working down.
I don't understand the meaning of the two folders "fastai" and "fasterai". Is this your own module? Why not choose to use conda install/pip install to download it? Could you give me some guiding advice? Thank you very much!!

 I try my best to reproduce your case. Because I am shocked by your case and want to promote it to more friends around me. But I have not been successful.
I sincerely hope to get your help.

**Comment by jantic** [comment]
So I think you're having problems that beget problems that beget problems here :)  First- that connection error you're seeing is probably just local to you and your computer trying to get that Pytorch package.  My advice on that would be to simply try again- after you update to the latest version of DeOldify.  I just added code to make sure that Pytorch 0.4.1 specifically is pulled instead of the new 1.0 version (haven't tested it yet but it was a very small change).

The syntax error that's being reported is most likely a symptom of not completing the conda install and having a python version older than when f strings were introduced (3.6).  

If your interest is just to colorize images and not train, I'd suggest using the Colab notebook instead (so much easier!):

https://colab.research.google.com/github/jantic/DeOldify/blob/master/DeOldify_colab.ipynb

They provide an 11 GB gpu..for free!  And zero hassle for you.  Do note I just realized the images being referenced on there for examples are broken (wtf).
