### ISSUE TITLE
Please tell me how to start this project by cpu?Thanks!

### ISSUE THREAD

**Issue by haoopan** [jantic/DeOldify#65]

**Comment by shahidul56** [comment]
don't think of it because it's need cuda acceleration to process pytorch task ..

**Comment by jantic** [comment]
@haoopan  This isn't -officially- supported yet but I think I can point you the way to making progress.

First, if you're asking for this because of a lack of suitable GPU on your end, I'd suggest using the Colab notebook instead (super easy to use, and comes with a free 11 GB GPU!):


https://github.com/jantic/DeOldify/issues/40
