### ISSUE TITLE
colorize_critic_128.h5 or colorize_critic_192.h5

### ISSUE THREAD

**Issue by miaoqiz** [jantic/DeOldify#72]
Hi,

Thanks for your excellent implementation!

Just wondering where can we download the pre-trained model for the discriminator?

**Comment by jantic** [comment]
It'll be available when I merge the FastAI v1 upgrade for DeOldify.  Which hopefully will be soon (within a month?).  But I'm working on some ambitious changes so this date isn't too firm.

**Comment by miaoqiz** [comment]
Hi,

Three quick questions:

1). Will the "c_lrs" and "g_lrs" decays inside each schedule? It seems like it changes based on the index of "szs" array and "lrs_unfreeze_factor".
2). Since the schedule is extendable, the graph is shared when schedule switching from "size=64" to "size=96",  from "size=160" to "size=192", and so forth. Is it correct?
3). Would you mind explaining what the role of "gen_freeze_tos" is?

Thanks a lot!

**Comment by jantic** [comment]
1)  The learning rates are constant once set so no they won' change.
2)  I'm not sure sure what you mean by graph.  
3)  gen_freeze_tos is determining whether or not the rensnet34 backbone is trainable.  When set to -1, then that means you're freezing the backbone.  Otherwise, all of the unet is trainable.
