### ISSUE TITLE
The speed for running ColorizeVisualization.ipynb is slow with GPU support even just for one picture

### ISSUE THREAD

**Issue by liuchangf** [jantic/DeOldify#76]
This is a great project , but when I run ColorizeVisualization.ipynb for my own picture (even only one) , it took a long time ( typically 3 minutes ) .  Do you guys get the same problems ? any idea to speed it ?

System :Ubuntu 16.04.5 LTS
Python Version: Python 3.6.6
GPU : GTX 1080 Ti
GPU Driver Version:396.54

**Comment by jantic** [comment]
That's not normal.  First thing I'd do is get nvidia-smi and check if your gpu is actually being hit (I doubt it).  It should take about 1 second per image if the gpu is being hit.  

If it's not being hit- if I remember correctly cuda device settings will be silently ignored and the rendering will go do cpu if gpu is not available (if for example you installed cpu pytorch or something like that).  So that brings me to the question- how did you install everything?

**Comment by liuchangf** [comment]
I create a VirtualEnv for the project , and install dependency with "pip install -r requirements.txt " in the environment .

Pytorch version in pip list as following :
torch              1.0.1.post2 
torchtext          0.2.3       
torchvision        0.2.2.post3

Some simple test in pytorch:
![image](https://user-images.githubusercontent.com/31433358/54178786-e574c700-44d1-11e9-9f3f-b4212eee8e12.png)

**Comment by liuchangf** [comment]
And the nvidia-smi -l  screenshots when run ColorizeVisualization.ipynb

![image](https://user-images.githubusercontent.com/31433358/54179033-924f4400-44d2-11e9-87b4-dfc04b81e2de.png)

**Comment by jantic** [comment]
Ok great this helps.  There's a few things I see going on.  First, the Pytorch version is not the expected version.  It should be 0.4.1.  I omitted that from requirements.txt and I don't remember why, but really I'd just install requirements using Anaconda.

```
 git clone https://github.com/jantic/DeOldify.git DeOldify
 cd DeOldify
 conda env create -f environment.yml
```

Then you'd start running with:

```
 source activate deoldify
 jupyter lab
```

I'll be once you install this way you'll have it up and running properly.

**Comment by liuchangf** [comment]
I'll try it, thank you :smile:
