### ISSUE TITLE
Did anybody has this error?  KeyError: 'layers.4.conv.0.weight_orig'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [jantic/DeOldify#78]
I'm trying to launch video_converter script. But something goes wrong. 
Could it be because I run it as regular python script, not as jyputer notebook?

```
import os
os.environ['CUDA_VISIBLE_DEVICES']='3'

import fastai
import ffmpeg
from fastai import *
from fastai.vision import *
from fastai.callbacks.tensorboard import *
from fastai.vision.gan import *
from fasterai.dataset import *
from fasterai.visualize import *
from fasterai.loss import *
from fasterai.filters import *
from fasterai.generators import *
from pathlib import Path
from itertools import repeat
from IPython.display import HTML, display
plt.style.use('dark_background')
torch.backends.cudnn.benchmark=True

render_factor=43

source_url = 'https://www.youtube.com/watch?v=gZShc8oshtU'

file_name = 'video14.mp4'
colorizer = get_video_colorizer2(render_factor=render_factor)


colorizer.colorize_from_url(source_url, file_name)
```

**Comment by jantic** [comment]
Based on the short snippet of the stack trace provided that would be the model weights being loaded not matching what the loading model expects.  I'm not going to tackle this yet though because this stuff isn't being published for public consumption yet but rather for cooperating with other developers (it's still in development as a separate branch).  I believe it'll be up in a few weeks.  So I just have to ask for patience on this one.

**Comment by zarifaziz** [comment]
I was also getting the same error but that was after setting 'artistic=False' on the Image Colab notebook. I even made sure I downloaded 'ColorizeStable_gen.pth'

**Comment by deus42** [comment]
Same
