### ISSUE TITLE
One quick question!

### ISSUE THREAD

**Issue by prnvjb** [jantic/DeOldify#82]
Hi,
If I train this net on only persons dataset, is there a higher chance of getting more positive results for person images at inference?
Thanks!!

**Comment by jantic** [comment]
The Singaporean government basically did that actually.  I asked directly about this- they said they used the same DeOldify model, but just trained on more people oriented data.  https://blog.data.gov.sg/bringing-black-and-white-photos-to-life-using-colourise-sg-435ae5cc5036

That being said, I can tell you what else does a great job of getting (much) better results on people- pretrained resnet101 backbone instead of resnet34.  This is actually what I'm using in my next release coming up soon.  You might just want to wait for that.
