### ISSUE TITLE
Add multi-GPU support

### ISSUE THREAD

**Issue by QuantScientist** [jantic/DeOldify#91]
Can you kindly use something like:
`
model = torch.nn.DataParallel(model, device_ids=range(torch.cuda.device_count()))
`

**Comment by jantic** [comment]
There isn't actually much to be gained here both in terms of performance and in terms of how many people will benefit from this.  Originally I wanted to do it but then later decided that focusing on one card support would be the most effective use of effort.  Reason- having multiple simultaneous experiments turns out to be much more important for productivity.  So if anybody wants to implement this and submit a pull request- great!  But I'm going to close this for now for the reasons above.
